services:
  osrm:
    image: osrm/osrm-backend:latest
    container_name: tow-osrm
    ports:
      - "5080:5000"
    volumes:
      - tow-osrm-data:/data
    command: osrm-routed --algorithm mld /data/russia-latest.osrm

volumes:
  tow-osrm-data:
