// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CarType string

const (
	CarTypeValue0 CarType = "Легковой"
	CarTypeValue1 CarType = "Внедорожник"
	CarTypeValue2 CarType = "Микроавтобус"
	CarTypeValue3 CarType = "Грузовик"
	CarTypeValue4 CarType = "Мотоцикл"
	CarTypeValue5 CarType = "Спецтехника"
	CarTypeValue6 CarType = "Электромобиль"
	CarTypeValue7 CarType = "Другое"
)

func (e *CarType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CarType(s)
	case string:
		*e = CarType(s)
	default:
		return fmt.Errorf("unsupported scan type for CarType: %T", src)
	}
	return nil
}

type NullCarType struct {
	CarType CarType
	Valid   bool // Valid is true if CarType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCarType) Scan(value interface{}) error {
	if value == nil {
		ns.CarType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CarType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCarType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CarType), nil
}

type OrderStatus string

const (
	OrderStatusForming    OrderStatus = "forming"
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusAccepted   OrderStatus = "accepted"
	OrderStatusInProgress OrderStatus = "in_progress"
	OrderStatusCompleted  OrderStatus = "completed"
	OrderStatusCancelled  OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Driver struct {
	UserID       int64
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	Name         string
	ProfileImage *string
	WorkStarts   *time.Time
	WorkEnds     *time.Time
	IsAvailable  bool
	LastSeen     pgtype.Timestamptz
	Location     interface{}
	Rating       *float32
	Phone        *string
	Address      *string
}

type MovingDriver struct {
	DriverID            int64
	UpdatedAt           *time.Time
	RealtimeLocation    interface{}
	TravelTime          time.Time
	PathMeters          int32
	CoarseH3            interface{}
	DestinationLocation interface{}
	DestinationTime     *time.Time
}

type Order struct {
	ID                   int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CustomerID           int64
	DriverID             *int64
	FromLocation         interface{}
	ToLocation           interface{}
	FromAddress          string
	ToAddress            string
	TotalDistanceMeters  *int32
	HowManyWheelsBlocked int16
	PriceRubles          *int32
	Status               OrderStatus
	AcceptedAt           *time.Time
	PickedUpAt           *time.Time
	CompletedAt          *time.Time
	CancelledAt          *time.Time
	CancellationReason   *string
	CarWeightKg          int32
	CarLengthMeters      float32
	CarType              CarType
	CarName              string
	CarPhotoUrl          *string
	CustomerMessage      *string
}

type PushSubscription struct {
	ID              int64
	UserID          int64
	Endpoint        string
	DevicePublicKey string
	AuthSecret      string
	DeviceType      string
	CreatedAt       time.Time
}

type Session struct {
	TokenHash string
	SessionID pgtype.UUID
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
	Roles     []string
}

type TowDriver struct {
	DriverID           int64
	MaxCarWeightKg     int32
	MaxCarLengthMeters float32
	CarPhotoMain       string
	CarPhotos          *string
}

type TowDriverFreelyAvailable struct {
	UserID       int64
	FromDate     time.Time
	ToDate       time.Time
	FromLocation interface{}
	FromAddress  string
	EnRouteOrder *bool
	TariffPerKm  *float32
}

type TowDriverFreelyAvailableToLocationList struct {
	ID        int64
	TowDriver int64
	Location  interface{}
	Address   string
}

type User struct {
	ID           int64
	CreatedAt    time.Time
	UpdatedAt    *time.Time
	DeletedAt    *time.Time
	Phone        *string
	Email        *string
	ProfileImage *string
	Roles        []string
}

type UserOauthLink struct {
	UserID     int64
	Provider   string
	ProviderID string
}
