// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Driver struct {
	UserID       int64
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	Name         string
	ProfileImage *string
	WorkStarts   *time.Time
	WorkEnds     *time.Time
	IsAvailable  bool
	LastSeen     pgtype.Timestamptz
	Location     interface{}
	Rating       *float32
}

type MovingDriver struct {
	DriverID            int64
	UpdatedAt           *time.Time
	RealtimeLocation    interface{}
	TravelTime          time.Time
	PathMeters          int32
	CoarseH3            interface{}
	DestinationLocation interface{}
	DestinationTime     *time.Time
}

type Session struct {
	TokenHash string
	SessionID pgtype.UUID
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
	Roles     []string
}

type TowDriverFreelyAvailable struct {
	UserID       int64
	FromDate     time.Time
	ToDate       time.Time
	FromLocation interface{}
	FromAddress  string
	EnRouteOrder *bool
	TariffPerKm  *float32
}

type TowDriverFreelyAvailableToLocationList struct {
	ID        int64
	TowDriver int64
	Location  interface{}
	Address   string
}

type User struct {
	ID           int64
	CreatedAt    time.Time
	UpdatedAt    *time.Time
	DeletedAt    *time.Time
	Phone        *string
	Email        *string
	ProfileImage *string
	Roles        []string
}

type UserOauthLink struct {
	UserID     int64
	Provider   string
	ProviderID string
}
