// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO session (token_hash, user_id, roles, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    int64
	Roles     []string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.Roles,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT session_id, user_id, roles, created_at, expires_at
FROM session
WHERE token_hash = $1 AND expires_at > NOW()
`

type GetSessionByTokenRow struct {
	SessionID pgtype.UUID
	UserID    int64
	Roles     []string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Roles,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
