// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"time"
)

const createOAuthLink = `-- name: CreateOAuthLink :exec
INSERT INTO user_oauth_links (user_id, provider, provider_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, provider) DO UPDATE SET provider_id = EXCLUDED.provider_id
`

type CreateOAuthLinkParams struct {
	UserID     int64
	Provider   string
	ProviderID string
}

func (q *Queries) CreateOAuthLink(ctx context.Context, arg CreateOAuthLinkParams) error {
	_, err := q.db.Exec(ctx, createOAuthLink, arg.UserID, arg.Provider, arg.ProviderID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (phone, email, created_at, updated_at)
VALUES ($1, $2, NOW(), NULL)
RETURNING id
`

type CreateUserParams struct {
	Phone *string
	Email *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Phone, arg.Email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone, email, profile_image, roles, created_at, updated_at
FROM "user"
WHERE email = $1::TEXT AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID           int64
	Phone        *string
	Email        *string
	ProfileImage *string
	Roles        []string
	CreatedAt    time.Time
	UpdatedAt    *time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.ProfileImage,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, email, profile_image, roles, created_at, updated_at
FROM "user"
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID           int64
	Phone        *string
	Email        *string
	ProfileImage *string
	Roles        []string
	CreatedAt    time.Time
	UpdatedAt    *time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.ProfileImage,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT u.id, u.phone, u.email, u.profile_image, u.roles, u.created_at, u.updated_at
FROM "user" u
JOIN user_oauth_links l ON u.id = l.user_id
WHERE l.provider = $1 AND l.provider_id = $2 AND u.deleted_at IS NULL
`

type GetUserByOAuthParams struct {
	Provider   string
	ProviderID string
}

type GetUserByOAuthRow struct {
	ID           int64
	Phone        *string
	Email        *string
	ProfileImage *string
	Roles        []string
	CreatedAt    time.Time
	UpdatedAt    *time.Time
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (GetUserByOAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserByOAuth, arg.Provider, arg.ProviderID)
	var i GetUserByOAuthRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.ProfileImage,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, email, profile_image, roles, created_at, updated_at
FROM "user"
WHERE phone = $1::TEXT AND deleted_at IS NULL
`

type GetUserByPhoneRow struct {
	ID           int64
	Phone        *string
	Email        *string
	ProfileImage *string
	Roles        []string
	CreatedAt    time.Time
	UpdatedAt    *time.Time
}

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.ProfileImage,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE "user" SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE "user" SET email = $2::TEXT, updated_at = NOW()
WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    int64
	Email string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
UPDATE "user" SET phone = $2::TEXT, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPhoneParams struct {
	ID    int64
	Phone string
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.Exec(ctx, updateUserPhone, arg.ID, arg.Phone)
	return err
}

const updateUserProfileImage = `-- name: UpdateUserProfileImage :exec
UPDATE "user" SET profile_image = $2::TEXT, updated_at = NOW()
WHERE id = $1
`

type UpdateUserProfileImageParams struct {
	ID           int64
	ProfileImage string
}

func (q *Queries) UpdateUserProfileImage(ctx context.Context, arg UpdateUserProfileImageParams) error {
	_, err := q.db.Exec(ctx, updateUserProfileImage, arg.ID, arg.ProfileImage)
	return err
}

const updateUserRoles = `-- name: UpdateUserRoles :exec
UPDATE "user" SET roles = $1::TEXT[], updated_at = NOW()
WHERE id = $2::BIGINT
`

type UpdateUserRolesParams struct {
	Roles  []string
	UserID int64
}

func (q *Queries) UpdateUserRoles(ctx context.Context, arg UpdateUserRolesParams) error {
	_, err := q.db.Exec(ctx, updateUserRoles, arg.Roles, arg.UserID)
	return err
}
