// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for CarInfoCarType.
const (
	CarInfoCarTypeВнедорожник   CarInfoCarType = "Внедорожник"
	CarInfoCarTypeГрузовик      CarInfoCarType = "Грузовик"
	CarInfoCarTypeДругое        CarInfoCarType = "Другое"
	CarInfoCarTypeЛегковой      CarInfoCarType = "Легковой"
	CarInfoCarTypeМикроавтобус  CarInfoCarType = "Микроавтобус"
	CarInfoCarTypeМотоцикл      CarInfoCarType = "Мотоцикл"
	CarInfoCarTypeСпецтехника   CarInfoCarType = "Спецтехника"
	CarInfoCarTypeЭлектромобиль CarInfoCarType = "Электромобиль"
)

// Defines values for CreateOrderRequestCarType.
const (
	CreateOrderRequestCarTypeВнедорожник   CreateOrderRequestCarType = "Внедорожник"
	CreateOrderRequestCarTypeГрузовик      CreateOrderRequestCarType = "Грузовик"
	CreateOrderRequestCarTypeДругое        CreateOrderRequestCarType = "Другое"
	CreateOrderRequestCarTypeЛегковой      CreateOrderRequestCarType = "Легковой"
	CreateOrderRequestCarTypeМикроавтобус  CreateOrderRequestCarType = "Микроавтобус"
	CreateOrderRequestCarTypeМотоцикл      CreateOrderRequestCarType = "Мотоцикл"
	CreateOrderRequestCarTypeСпецтехника   CreateOrderRequestCarType = "Спецтехника"
	CreateOrderRequestCarTypeЭлектромобиль CreateOrderRequestCarType = "Электромобиль"
)

// Defines values for OrderCarType.
const (
	OrderCarTypeВнедорожник   OrderCarType = "Внедорожник"
	OrderCarTypeГрузовик      OrderCarType = "Грузовик"
	OrderCarTypeДругое        OrderCarType = "Другое"
	OrderCarTypeЛегковой      OrderCarType = "Легковой"
	OrderCarTypeМикроавтобус  OrderCarType = "Микроавтобус"
	OrderCarTypeМотоцикл      OrderCarType = "Мотоцикл"
	OrderCarTypeСпецтехника   OrderCarType = "Спецтехника"
	OrderCarTypeЭлектромобиль OrderCarType = "Электромобиль"
)

// Defines values for OrderStatus.
const (
	OrderStatusAccepted   OrderStatus = "accepted"
	OrderStatusCancelled  OrderStatus = "cancelled"
	OrderStatusCompleted  OrderStatus = "completed"
	OrderStatusForming    OrderStatus = "forming"
	OrderStatusInProgress OrderStatus = "in_progress"
	OrderStatusPending    OrderStatus = "pending"
)

// Defines values for UpdateOrderRequestCarType.
const (
	UpdateOrderRequestCarTypeВнедорожник   UpdateOrderRequestCarType = "Внедорожник"
	UpdateOrderRequestCarTypeГрузовик      UpdateOrderRequestCarType = "Грузовик"
	UpdateOrderRequestCarTypeДругое        UpdateOrderRequestCarType = "Другое"
	UpdateOrderRequestCarTypeЛегковой      UpdateOrderRequestCarType = "Легковой"
	UpdateOrderRequestCarTypeМикроавтобус  UpdateOrderRequestCarType = "Микроавтобус"
	UpdateOrderRequestCarTypeМотоцикл      UpdateOrderRequestCarType = "Мотоцикл"
	UpdateOrderRequestCarTypeСпецтехника   UpdateOrderRequestCarType = "Спецтехника"
	UpdateOrderRequestCarTypeЭлектромобиль UpdateOrderRequestCarType = "Электромобиль"
)

// Defines values for UpdateOrderStatusRequestStatus.
const (
	UpdateOrderStatusRequestStatusAccepted   UpdateOrderStatusRequestStatus = "accepted"
	UpdateOrderStatusRequestStatusCancelled  UpdateOrderStatusRequestStatus = "cancelled"
	UpdateOrderStatusRequestStatusCompleted  UpdateOrderStatusRequestStatus = "completed"
	UpdateOrderStatusRequestStatusForming    UpdateOrderStatusRequestStatus = "forming"
	UpdateOrderStatusRequestStatusInProgress UpdateOrderStatusRequestStatus = "in_progress"
	UpdateOrderStatusRequestStatusPending    UpdateOrderStatusRequestStatus = "pending"
)

// Defines values for ListMyOrdersParamsRole.
const (
	Customer ListMyOrdersParamsRole = "customer"
	Driver   ListMyOrdersParamsRole = "driver"
)

// CarInfo defines model for CarInfo.
type CarInfo struct {
	CarLengthMeters float32        `json:"car_length_meters"`
	CarName         string         `json:"car_name"`
	CarPhotoUrl     *string        `json:"car_photo_url"`
	CarType         CarInfoCarType `json:"car_type"`
	CarWeightKg     int            `json:"car_weight_kg"`
	CustomerMessage *string        `json:"customer_message"`
}

// CarInfoCarType defines model for CarInfo.CarType.
type CarInfoCarType string

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	CarLengthMeters      float32                   `json:"car_length_meters"`
	CarName              string                    `json:"car_name"`
	CarPhotoUrl          *string                   `json:"car_photo_url"`
	CarType              CreateOrderRequestCarType `json:"car_type"`
	CarWeightKg          int                       `json:"car_weight_kg"`
	CustomerMessage      *string                   `json:"customer_message"`
	FromAddress          *string                   `json:"from_address,omitempty"`
	FromLat              float32                   `json:"from_lat"`
	FromLon              float32                   `json:"from_lon"`
	HowManyWheelsBlocked int                       `json:"how_many_wheels_blocked"`
	PriceRubles          *int                      `json:"price_rubles"`
	ToAddress            *string                   `json:"to_address,omitempty"`
	ToLat                float32                   `json:"to_lat"`
	ToLon                float32                   `json:"to_lon"`
	TotalDistanceMeters  *int                      `json:"total_distance_meters"`
}

// CreateOrderRequestCarType defines model for CreateOrderRequest.CarType.
type CreateOrderRequestCarType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// Order defines model for Order.
type Order struct {
	AcceptedAt           *time.Time   `json:"accepted_at"`
	CancellationReason   *string      `json:"cancellation_reason"`
	CancelledAt          *time.Time   `json:"cancelled_at"`
	CarLengthMeters      float32      `json:"car_length_meters"`
	CarName              string       `json:"car_name"`
	CarPhotoUrl          *string      `json:"car_photo_url"`
	CarType              OrderCarType `json:"car_type"`
	CarWeightKg          int          `json:"car_weight_kg"`
	CompletedAt          *time.Time   `json:"completed_at"`
	CreatedAt            time.Time    `json:"created_at"`
	CustomerId           int64        `json:"customer_id"`
	CustomerMessage      *string      `json:"customer_message"`
	DriverId             *int64       `json:"driver_id"`
	FromAddress          *string      `json:"from_address,omitempty"`
	FromLat              float32      `json:"from_lat"`
	FromLon              float32      `json:"from_lon"`
	HowManyWheelsBlocked int          `json:"how_many_wheels_blocked"`
	Id                   int64        `json:"id"`
	PickedUpAt           *time.Time   `json:"picked_up_at"`
	PriceRubles          *int         `json:"price_rubles"`
	Status               OrderStatus  `json:"status"`
	ToAddress            *string      `json:"to_address,omitempty"`
	ToLat                float32      `json:"to_lat"`
	ToLon                float32      `json:"to_lon"`
	TotalDistanceMeters  *int         `json:"total_distance_meters"`
	UpdatedAt            time.Time    `json:"updated_at"`
}

// OrderCarType defines model for Order.CarType.
type OrderCarType string

// OrderStatus defines model for Order.Status.
type OrderStatus string

// UpdateOrderRequest defines model for UpdateOrderRequest.
type UpdateOrderRequest struct {
	CarLengthMeters      float32                   `json:"car_length_meters"`
	CarName              string                    `json:"car_name"`
	CarPhotoUrl          *string                   `json:"car_photo_url"`
	CarType              UpdateOrderRequestCarType `json:"car_type"`
	CarWeightKg          int                       `json:"car_weight_kg"`
	CustomerMessage      *string                   `json:"customer_message"`
	FromAddress          *string                   `json:"from_address,omitempty"`
	FromLat              float32                   `json:"from_lat"`
	FromLon              float32                   `json:"from_lon"`
	HowManyWheelsBlocked int                       `json:"how_many_wheels_blocked"`
	PriceRubles          *int                      `json:"price_rubles"`
	ToAddress            *string                   `json:"to_address,omitempty"`
	ToLat                float32                   `json:"to_lat"`
	ToLon                float32                   `json:"to_lon"`
	TotalDistanceMeters  *int                      `json:"total_distance_meters"`
}

// UpdateOrderRequestCarType defines model for UpdateOrderRequest.CarType.
type UpdateOrderRequestCarType string

// UpdateOrderStatusRequest defines model for UpdateOrderStatusRequest.
type UpdateOrderStatusRequest struct {
	CancellationReason *string                        `json:"cancellation_reason,omitempty"`
	Status             UpdateOrderStatusRequestStatus `json:"status"`
}

// UpdateOrderStatusRequestStatus defines model for UpdateOrderStatusRequest.Status.
type UpdateOrderStatusRequestStatus string

// ListMyOrdersParams defines parameters for ListMyOrders.
type ListMyOrdersParams struct {
	Role ListMyOrdersParamsRole `form:"role" json:"role"`
}

// ListMyOrdersParamsRole defines parameters for ListMyOrders.
type ListMyOrdersParamsRole string

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// UpdateOrderJSONRequestBody defines body for UpdateOrder for application/json ContentType.
type UpdateOrderJSONRequestBody = UpdateOrderRequest

// UpdateOrderStatusJSONRequestBody defines body for UpdateOrderStatus for application/json ContentType.
type UpdateOrderStatusJSONRequestBody = UpdateOrderStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new tow order
	// (POST /order)
	CreateOrder(c *gin.Context)
	// List orders for the authenticated user
	// (GET /order/my)
	ListMyOrders(c *gin.Context, params ListMyOrdersParams)
	// Delete user's active (forming/pending) order
	// (DELETE /order/my/active)
	DeleteMyActiveOrder(c *gin.Context)
	// Get order by ID
	// (GET /order/{order_id})
	GetOrder(c *gin.Context, orderId int64)
	// Update order details (forming/pending only)
	// (PUT /order/{order_id})
	UpdateOrder(c *gin.Context, orderId int64)
	// Update order status
	// (PATCH /order/{order_id}/status)
	UpdateOrderStatus(c *gin.Context, orderId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrder(c)
}

// ListMyOrders operation middleware
func (siw *ServerInterfaceWrapper) ListMyOrders(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMyOrdersParams

	// ------------- Required query parameter "role" -------------

	if paramValue := c.Query("role"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument role is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "role", c.Request.URL.Query(), &params.Role)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter role: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyOrders(c, params)
}

// DeleteMyActiveOrder operation middleware
func (siw *ServerInterfaceWrapper) DeleteMyActiveOrder(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteMyActiveOrder(c)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId int64

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", c.Param("order_id"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter order_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrder(c, orderId)
}

// UpdateOrder operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId int64

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", c.Param("order_id"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter order_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOrder(c, orderId)
}

// UpdateOrderStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrderStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId int64

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", c.Param("order_id"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter order_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOrderStatus(c, orderId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/order", wrapper.CreateOrder)
	router.GET(options.BaseURL+"/order/my", wrapper.ListMyOrders)
	router.DELETE(options.BaseURL+"/order/my/active", wrapper.DeleteMyActiveOrder)
	router.GET(options.BaseURL+"/order/:order_id", wrapper.GetOrder)
	router.PUT(options.BaseURL+"/order/:order_id", wrapper.UpdateOrder)
	router.PATCH(options.BaseURL+"/order/:order_id/status", wrapper.UpdateOrderStatus)
}

type CreateOrderRequestObject struct {
	Body *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder201JSONResponse Order

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder400JSONResponse ErrorResponse

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder401Response struct {
}

func (response CreateOrder401Response) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListMyOrdersRequestObject struct {
	Params ListMyOrdersParams
}

type ListMyOrdersResponseObject interface {
	VisitListMyOrdersResponse(w http.ResponseWriter) error
}

type ListMyOrders200JSONResponse struct {
	Orders *[]Order `json:"orders,omitempty"`
}

func (response ListMyOrders200JSONResponse) VisitListMyOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListMyOrders401Response struct {
}

func (response ListMyOrders401Response) VisitListMyOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteMyActiveOrderRequestObject struct {
}

type DeleteMyActiveOrderResponseObject interface {
	VisitDeleteMyActiveOrderResponse(w http.ResponseWriter) error
}

type DeleteMyActiveOrder204Response struct {
}

func (response DeleteMyActiveOrder204Response) VisitDeleteMyActiveOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteMyActiveOrder400JSONResponse ErrorResponse

func (response DeleteMyActiveOrder400JSONResponse) VisitDeleteMyActiveOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteMyActiveOrder401Response struct {
}

func (response DeleteMyActiveOrder401Response) VisitDeleteMyActiveOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetOrderRequestObject struct {
	OrderId int64 `json:"order_id"`
}

type GetOrderResponseObject interface {
	VisitGetOrderResponse(w http.ResponseWriter) error
}

type GetOrder200JSONResponse Order

func (response GetOrder200JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrder401Response struct {
}

func (response GetOrder401Response) VisitGetOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetOrder404Response struct {
}

func (response GetOrder404Response) VisitGetOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateOrderRequestObject struct {
	OrderId int64 `json:"order_id"`
	Body    *UpdateOrderJSONRequestBody
}

type UpdateOrderResponseObject interface {
	VisitUpdateOrderResponse(w http.ResponseWriter) error
}

type UpdateOrder200JSONResponse Order

func (response UpdateOrder200JSONResponse) VisitUpdateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrder400JSONResponse ErrorResponse

func (response UpdateOrder400JSONResponse) VisitUpdateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrder401Response struct {
}

func (response UpdateOrder401Response) VisitUpdateOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateOrder404Response struct {
}

func (response UpdateOrder404Response) VisitUpdateOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateOrderStatusRequestObject struct {
	OrderId int64 `json:"order_id"`
	Body    *UpdateOrderStatusJSONRequestBody
}

type UpdateOrderStatusResponseObject interface {
	VisitUpdateOrderStatusResponse(w http.ResponseWriter) error
}

type UpdateOrderStatus200JSONResponse Order

func (response UpdateOrderStatus200JSONResponse) VisitUpdateOrderStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrderStatus400JSONResponse ErrorResponse

func (response UpdateOrderStatus400JSONResponse) VisitUpdateOrderStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrderStatus401Response struct {
}

func (response UpdateOrderStatus401Response) VisitUpdateOrderStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateOrderStatus404Response struct {
}

func (response UpdateOrderStatus404Response) VisitUpdateOrderStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new tow order
	// (POST /order)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// List orders for the authenticated user
	// (GET /order/my)
	ListMyOrders(ctx context.Context, request ListMyOrdersRequestObject) (ListMyOrdersResponseObject, error)
	// Delete user's active (forming/pending) order
	// (DELETE /order/my/active)
	DeleteMyActiveOrder(ctx context.Context, request DeleteMyActiveOrderRequestObject) (DeleteMyActiveOrderResponseObject, error)
	// Get order by ID
	// (GET /order/{order_id})
	GetOrder(ctx context.Context, request GetOrderRequestObject) (GetOrderResponseObject, error)
	// Update order details (forming/pending only)
	// (PUT /order/{order_id})
	UpdateOrder(ctx context.Context, request UpdateOrderRequestObject) (UpdateOrderResponseObject, error)
	// Update order status
	// (PATCH /order/{order_id}/status)
	UpdateOrderStatus(ctx context.Context, request UpdateOrderStatusRequestObject) (UpdateOrderStatusResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(ctx *gin.Context) {
	var request CreateOrderRequestObject

	var body CreateOrderJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyOrders operation middleware
func (sh *strictHandler) ListMyOrders(ctx *gin.Context, params ListMyOrdersParams) {
	var request ListMyOrdersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyOrders(ctx, request.(ListMyOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyOrders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListMyOrdersResponseObject); ok {
		if err := validResponse.VisitListMyOrdersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteMyActiveOrder operation middleware
func (sh *strictHandler) DeleteMyActiveOrder(ctx *gin.Context) {
	var request DeleteMyActiveOrderRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMyActiveOrder(ctx, request.(DeleteMyActiveOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMyActiveOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteMyActiveOrderResponseObject); ok {
		if err := validResponse.VisitDeleteMyActiveOrderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrder operation middleware
func (sh *strictHandler) GetOrder(ctx *gin.Context, orderId int64) {
	var request GetOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrder(ctx, request.(GetOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetOrderResponseObject); ok {
		if err := validResponse.VisitGetOrderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrder operation middleware
func (sh *strictHandler) UpdateOrder(ctx *gin.Context, orderId int64) {
	var request UpdateOrderRequestObject

	request.OrderId = orderId

	var body UpdateOrderJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrder(ctx, request.(UpdateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateOrderResponseObject); ok {
		if err := validResponse.VisitUpdateOrderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrderStatus operation middleware
func (sh *strictHandler) UpdateOrderStatus(ctx *gin.Context, orderId int64) {
	var request UpdateOrderStatusRequestObject

	request.OrderId = orderId

	var body UpdateOrderStatusJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrderStatus(ctx, request.(UpdateOrderStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrderStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateOrderStatusResponseObject); ok {
		if err := validResponse.VisitUpdateOrderStatusResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
