// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.9
//   protoc               v7.35.1
// source: gps_get.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb";

export interface DriverRealtime {
  driverId: number;
  distance: number;
  time: number;
  /** repeated float points = 4; */
  points: Coordinates[];
}

export interface Coordinates {
  /**
   * float latitude = 1;
   * float longitude = 2;
   */
  coordinates: number[];
}

function createBaseDriverRealtime(): DriverRealtime {
  return { driverId: 0, distance: 0, time: 0, points: [] };
}

export const DriverRealtime: MessageFns<DriverRealtime> = {
  encode(message: DriverRealtime, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== 0) {
      writer.uint32(8).uint32(message.driverId);
    }
    if (message.distance !== 0) {
      writer.uint32(21).float(message.distance);
    }
    if (message.time !== 0) {
      writer.uint32(24).uint32(message.time);
    }
    for (const v of message.points) {
      Coordinates.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriverRealtime {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriverRealtime();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.driverId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.distance = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.time = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.points.push(Coordinates.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriverRealtime {
    return {
      driverId: isSet(object.driverId)
        ? globalThis.Number(object.driverId)
        : isSet(object.driver_id)
        ? globalThis.Number(object.driver_id)
        : 0,
      distance: isSet(object.distance) ? globalThis.Number(object.distance) : 0,
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
      points: globalThis.Array.isArray(object?.points) ? object.points.map((e: any) => Coordinates.fromJSON(e)) : [],
    };
  },

  toJSON(message: DriverRealtime): unknown {
    const obj: any = {};
    if (message.driverId !== 0) {
      obj.driverId = Math.round(message.driverId);
    }
    if (message.distance !== 0) {
      obj.distance = message.distance;
    }
    if (message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    if (message.points?.length) {
      obj.points = message.points.map((e) => Coordinates.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriverRealtime>, I>>(base?: I): DriverRealtime {
    return DriverRealtime.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriverRealtime>, I>>(object: I): DriverRealtime {
    const message = createBaseDriverRealtime();
    message.driverId = object.driverId ?? 0;
    message.distance = object.distance ?? 0;
    message.time = object.time ?? 0;
    message.points = object.points?.map((e) => Coordinates.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCoordinates(): Coordinates {
  return { coordinates: [] };
}

export const Coordinates: MessageFns<Coordinates> = {
  encode(message: Coordinates, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.coordinates) {
      writer.float(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Coordinates {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoordinates();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.coordinates.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.coordinates.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Coordinates {
    return {
      coordinates: globalThis.Array.isArray(object?.coordinates)
        ? object.coordinates.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: Coordinates): unknown {
    const obj: any = {};
    if (message.coordinates?.length) {
      obj.coordinates = message.coordinates;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Coordinates>, I>>(base?: I): Coordinates {
    return Coordinates.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Coordinates>, I>>(object: I): Coordinates {
    const message = createBaseCoordinates();
    message.coordinates = object.coordinates?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
