// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.9
//   protoc               v7.35.1
// source: gps_get.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb";

export interface MovingDriver {
  driverId: number;
  pathMeters: number;
  travelTime: number;
  lat: number;
  lon: number;
  points: Coordinates[];
}

export interface Coordinates {
  /**
   * float latitude = 1;
   * float longitude = 2;
   */
  coordinates: number[];
}

function createBaseMovingDriver(): MovingDriver {
  return { driverId: 0, pathMeters: 0, travelTime: 0, lat: 0, lon: 0, points: [] };
}

export const MovingDriver: MessageFns<MovingDriver> = {
  encode(message: MovingDriver, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== 0) {
      writer.uint32(8).int64(message.driverId);
    }
    if (message.pathMeters !== 0) {
      writer.uint32(16).uint32(message.pathMeters);
    }
    if (message.travelTime !== 0) {
      writer.uint32(24).uint32(message.travelTime);
    }
    if (message.lat !== 0) {
      writer.uint32(45).float(message.lat);
    }
    if (message.lon !== 0) {
      writer.uint32(53).float(message.lon);
    }
    for (const v of message.points) {
      Coordinates.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MovingDriver {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMovingDriver();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.driverId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pathMeters = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.travelTime = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.lat = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.lon = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.points.push(Coordinates.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MovingDriver {
    return {
      driverId: isSet(object.driverId)
        ? globalThis.Number(object.driverId)
        : isSet(object.driver_id)
        ? globalThis.Number(object.driver_id)
        : 0,
      pathMeters: isSet(object.pathMeters)
        ? globalThis.Number(object.pathMeters)
        : isSet(object.path_meters)
        ? globalThis.Number(object.path_meters)
        : 0,
      travelTime: isSet(object.travelTime)
        ? globalThis.Number(object.travelTime)
        : isSet(object.travel_time)
        ? globalThis.Number(object.travel_time)
        : 0,
      lat: isSet(object.lat) ? globalThis.Number(object.lat) : 0,
      lon: isSet(object.lon) ? globalThis.Number(object.lon) : 0,
      points: globalThis.Array.isArray(object?.points) ? object.points.map((e: any) => Coordinates.fromJSON(e)) : [],
    };
  },

  toJSON(message: MovingDriver): unknown {
    const obj: any = {};
    if (message.driverId !== 0) {
      obj.driverId = Math.round(message.driverId);
    }
    if (message.pathMeters !== 0) {
      obj.pathMeters = Math.round(message.pathMeters);
    }
    if (message.travelTime !== 0) {
      obj.travelTime = Math.round(message.travelTime);
    }
    if (message.lat !== 0) {
      obj.lat = message.lat;
    }
    if (message.lon !== 0) {
      obj.lon = message.lon;
    }
    if (message.points?.length) {
      obj.points = message.points.map((e) => Coordinates.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MovingDriver>, I>>(base?: I): MovingDriver {
    return MovingDriver.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MovingDriver>, I>>(object: I): MovingDriver {
    const message = createBaseMovingDriver();
    message.driverId = object.driverId ?? 0;
    message.pathMeters = object.pathMeters ?? 0;
    message.travelTime = object.travelTime ?? 0;
    message.lat = object.lat ?? 0;
    message.lon = object.lon ?? 0;
    message.points = object.points?.map((e) => Coordinates.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCoordinates(): Coordinates {
  return { coordinates: [] };
}

export const Coordinates: MessageFns<Coordinates> = {
  encode(message: Coordinates, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.coordinates) {
      writer.float(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Coordinates {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoordinates();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.coordinates.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.coordinates.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Coordinates {
    return {
      coordinates: globalThis.Array.isArray(object?.coordinates)
        ? object.coordinates.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: Coordinates): unknown {
    const obj: any = {};
    if (message.coordinates?.length) {
      obj.coordinates = message.coordinates;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Coordinates>, I>>(base?: I): Coordinates {
    return Coordinates.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Coordinates>, I>>(object: I): Coordinates {
    const message = createBaseCoordinates();
    message.coordinates = object.coordinates?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
