services:
  postgres:
    image: postgis-h3:pg18-3.6
    container_name: tow-postgres-postgis-h3-ssl
    restart: unless-stopped
    environment:
      POSTGRES_DB: tow-service-db
      POSTGRES_USER: tow-service
      POSTGRES_PASSWORD: tow-service-password
    ports:
      - "5432:5432"
    volumes:
      - tow-postgis-data:/var/lib/postgresql/18/docker
      - ./certs/server.crt:/certs/server.crt:ro
      - ./certs/server.key:/certs/server.key:ro
    command: -c ssl=on -c ssl_cert_file=/certs/server.crt -c ssl_key_file=/certs/server.key
    networks:
      tow-network:

volumes:
  tow-postgis-data:

networks:
  tow-network:
    driver: bridge
    name: tow-network
