// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDriver = `-- name: CreateDriver :exec
INSERT INTO
	driver (
		user_id,
		name,
		phone,
		work_starts,
		work_ends,
		location,
		rating,
		address
	) VALUES ($1, $2, $3, $4, $5, ST_SetSRID(ST_MakePoint($8::REAL, $9::REAL), 4326), $6, $7)
`

type CreateDriverParams struct {
	UserID     int64
	Name       string
	Phone      *string
	WorkStarts *time.Time
	WorkEnds   *time.Time
	Rating     *float32
	Address    *string
	Lon        float32
	Lat        float32
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) error {
	_, err := q.db.Exec(ctx, createDriver,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.WorkStarts,
		arg.WorkEnds,
		arg.Rating,
		arg.Address,
		arg.Lon,
		arg.Lat,
	)
	return err
}

const createTowDriver = `-- name: CreateTowDriver :exec
INSERT INTO tow_driver (driver_id, max_car_weight_kg, max_car_length_meters)
VALUES ($1, $2, $3)
`

type CreateTowDriverParams struct {
	DriverID           int64
	MaxCarWeightKg     int32
	MaxCarLengthMeters float32
}

func (q *Queries) CreateTowDriver(ctx context.Context, arg CreateTowDriverParams) error {
	_, err := q.db.Exec(ctx, createTowDriver, arg.DriverID, arg.MaxCarWeightKg, arg.MaxCarLengthMeters)
	return err
}

const getDriverByUserID = `-- name: GetDriverByUserID :one
SELECT
	d.user_id,
	d.name,
	d.phone,
	d.profile_image,
	d.work_starts,
	d.work_ends,
	d.is_available,
	d.last_seen,
	d.rating,
	ST_X(d.location::geometry)::REAL as lon,
	ST_Y(d.location::geometry)::REAL as lat,
	COALESCE(t.max_car_weight_kg, 0) as max_car_weight_kg,
	COALESCE(t.max_car_length_meters, 0) as max_car_length_meters,
	COALESCE(d.address, '') as address,
	COALESCE(t.car_photo_main, '') as car_photo_main,
	t.car_photos
FROM driver d
LEFT JOIN tow_driver t ON t.driver_id = d.user_id
WHERE d.user_id = $1
`

type GetDriverByUserIDRow struct {
	UserID             int64
	Name               string
	Phone              *string
	ProfileImage       *string
	WorkStarts         *time.Time
	WorkEnds           *time.Time
	IsAvailable        bool
	LastSeen           pgtype.Timestamptz
	Rating             *float32
	Lon                float32
	Lat                float32
	MaxCarWeightKg     int32
	MaxCarLengthMeters float32
	Address            string
	CarPhotoMain       string
	CarPhotos          *string
}

func (q *Queries) GetDriverByUserID(ctx context.Context, userID int64) (GetDriverByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getDriverByUserID, userID)
	var i GetDriverByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.ProfileImage,
		&i.WorkStarts,
		&i.WorkEnds,
		&i.IsAvailable,
		&i.LastSeen,
		&i.Rating,
		&i.Lon,
		&i.Lat,
		&i.MaxCarWeightKg,
		&i.MaxCarLengthMeters,
		&i.Address,
		&i.CarPhotoMain,
		&i.CarPhotos,
	)
	return i, err
}

const getFilteredDrivers = `-- name: GetFilteredDrivers :many
SELECT 
    d.user_id,
	d.name,
	d.phone,
	d.profile_image,
    d.work_starts, 
    d.work_ends, 
	d.is_available,
	d.last_seen,
    d.rating, 
	ST_X(d.location::GEOMETRY)::REAL AS lon,
	ST_Y(d.location::GEOMETRY)::REAL AS lat,
    st_distance(
        d.location, 
        st_setsrid(
            st_makepoint($1::REAL, $2::REAL), 
            4326
        )::geometry
    )::real AS distance,
	COALESCE(t.max_car_weight_kg, 0) as max_car_weight_kg,
	COALESCE(t.max_car_length_meters, 0) as max_car_length_meters,
	COALESCE(d.address, '') as address,
	COALESCE(t.car_photo_main, '') as car_photo_main,
	t.car_photos
FROM driver d
LEFT JOIN tow_driver t ON t.driver_id = d.user_id
WHERE 
    ($3::TIME IS NULL OR d.work_starts <= $3)
    AND ($4::TIME IS NULL OR d.work_ends >= $4)
    AND ($5::REAL IS NULL OR d.rating >= $5)
ORDER BY distance
`

type GetFilteredDriversParams struct {
	Lon        float32
	Lat        float32
	WorkStarts *time.Time
	WorkEnds   *time.Time
	MinRating  *float32
}

type GetFilteredDriversRow struct {
	UserID             int64
	Name               string
	Phone              *string
	ProfileImage       *string
	WorkStarts         *time.Time
	WorkEnds           *time.Time
	IsAvailable        bool
	LastSeen           pgtype.Timestamptz
	Rating             *float32
	Lon                float32
	Lat                float32
	Distance           float32
	MaxCarWeightKg     int32
	MaxCarLengthMeters float32
	Address            string
	CarPhotoMain       string
	CarPhotos          *string
}

func (q *Queries) GetFilteredDrivers(ctx context.Context, arg GetFilteredDriversParams) ([]GetFilteredDriversRow, error) {
	rows, err := q.db.Query(ctx, getFilteredDrivers,
		arg.Lon,
		arg.Lat,
		arg.WorkStarts,
		arg.WorkEnds,
		arg.MinRating,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilteredDriversRow
	for rows.Next() {
		var i GetFilteredDriversRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.ProfileImage,
			&i.WorkStarts,
			&i.WorkEnds,
			&i.IsAvailable,
			&i.LastSeen,
			&i.Rating,
			&i.Lon,
			&i.Lat,
			&i.Distance,
			&i.MaxCarWeightKg,
			&i.MaxCarLengthMeters,
			&i.Address,
			&i.CarPhotoMain,
			&i.CarPhotos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriver = `-- name: UpdateDriver :exec
UPDATE driver
SET name = $2, phone = $3, work_starts = $4, work_ends = $5,
    location = ST_SetSRID(ST_MakePoint($6::REAL, $7::REAL), 4326),
    address = $8,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateDriverParams struct {
	UserID     int64
	Name       string
	Phone      *string
	WorkStarts *time.Time
	WorkEnds   *time.Time
	Column6    float32
	Column7    float32
	Address    *string
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) error {
	_, err := q.db.Exec(ctx, updateDriver,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.WorkStarts,
		arg.WorkEnds,
		arg.Column6,
		arg.Column7,
		arg.Address,
	)
	return err
}

const updateDriverProfileImage = `-- name: UpdateDriverProfileImage :exec
UPDATE driver
SET profile_image = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateDriverProfileImageParams struct {
	UserID       int64
	ProfileImage *string
}

func (q *Queries) UpdateDriverProfileImage(ctx context.Context, arg UpdateDriverProfileImageParams) error {
	_, err := q.db.Exec(ctx, updateDriverProfileImage, arg.UserID, arg.ProfileImage)
	return err
}

const upsertTowDriver = `-- name: UpsertTowDriver :exec
INSERT INTO tow_driver (driver_id, max_car_weight_kg, max_car_length_meters, car_photo_main, car_photos)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (driver_id) DO UPDATE SET
	max_car_weight_kg = EXCLUDED.max_car_weight_kg,
	max_car_length_meters = EXCLUDED.max_car_length_meters,
	car_photo_main = EXCLUDED.car_photo_main,
	car_photos = EXCLUDED.car_photos
`

type UpsertTowDriverParams struct {
	DriverID           int64
	MaxCarWeightKg     int32
	MaxCarLengthMeters float32
	CarPhotoMain       string
	CarPhotos          *string
}

func (q *Queries) UpsertTowDriver(ctx context.Context, arg UpsertTowDriverParams) error {
	_, err := q.db.Exec(ctx, upsertTowDriver,
		arg.DriverID,
		arg.MaxCarWeightKg,
		arg.MaxCarLengthMeters,
		arg.CarPhotoMain,
		arg.CarPhotos,
	)
	return err
}
