// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDriver = `-- name: CreateDriver :one
INSERT INTO
	driver (
		user_id,
		name,
		work_starts,
		work_ends,
		location,
		rating
	) VALUES ($1, $2, $3, $4, ST_SetSRID(ST_MakePoint($6::REAL, $7::REAL), 4326), $5)
RETURNING id
`

type CreateDriverParams struct {
	UserID     int64
	Name       string
	WorkStarts *time.Time
	WorkEnds   *time.Time
	Rating     *float32
	Lon        float32
	Lat        float32
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (uint32, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.UserID,
		arg.Name,
		arg.WorkStarts,
		arg.WorkEnds,
		arg.Rating,
		arg.Lon,
		arg.Lat,
	)
	var id uint32
	err := row.Scan(&id)
	return id, err
}

const getDriverByID = `-- name: GetDriverByID :one
SELECT
	id,
	work_starts,
	work_ends,
	rating,
	ST_X(location::geometry)::REAL as lon,
	ST_Y(location::geometry)::REAL as lat
FROM driver
WHERE id = $1
`

type GetDriverByIDRow struct {
	ID         uint32
	WorkStarts *time.Time
	WorkEnds   *time.Time
	Rating     *float32
	Lon        float32
	Lat        float32
}

func (q *Queries) GetDriverByID(ctx context.Context, id uint32) (GetDriverByIDRow, error) {
	row := q.db.QueryRow(ctx, getDriverByID, id)
	var i GetDriverByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkStarts,
		&i.WorkEnds,
		&i.Rating,
		&i.Lon,
		&i.Lat,
	)
	return i, err
}

const getDriverByUserID = `-- name: GetDriverByUserID :one
SELECT
	id,
	user_id,
	name,
	profile_image,
	work_starts,
	work_ends,
	is_available,
	last_seen,
	rating,
	ST_X(location::geometry)::REAL as lon,
	ST_Y(location::geometry)::REAL as lat
FROM driver
WHERE user_id = $1
`

type GetDriverByUserIDRow struct {
	ID           uint32
	UserID       int64
	Name         string
	ProfileImage *string
	WorkStarts   *time.Time
	WorkEnds     *time.Time
	IsAvailable  bool
	LastSeen     pgtype.Timestamptz
	Rating       *float32
	Lon          float32
	Lat          float32
}

func (q *Queries) GetDriverByUserID(ctx context.Context, userID int64) (GetDriverByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getDriverByUserID, userID)
	var i GetDriverByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ProfileImage,
		&i.WorkStarts,
		&i.WorkEnds,
		&i.IsAvailable,
		&i.LastSeen,
		&i.Rating,
		&i.Lon,
		&i.Lat,
	)
	return i, err
}

const getFilteredDrivers = `-- name: GetFilteredDrivers :many
SELECT 
    id,
	name,
    work_starts, 
    work_ends, 
    rating, 
	ST_X(location::GEOMETRY)::REAL AS lon,
	ST_Y(location::GEOMETRY)::REAL AS lat,
    st_distance(
        location, 
        st_setsrid(
            st_makepoint($1::REAL, $2::REAL), 
            4326
        )::geometry
    )::real AS distance
FROM driver
WHERE 
    ($3::TIME IS NULL OR work_starts <= $3)
    AND ($4::TIME IS NULL OR work_ends >= $4)
    AND ($5::REAL IS NULL OR rating >= $5)
ORDER BY distance
`

type GetFilteredDriversParams struct {
	Lat        float32
	Lon        float32
	WorkStarts *time.Time
	WorkEnds   *time.Time
	MinRating  *float32
}

type GetFilteredDriversRow struct {
	ID         uint32
	Name       string
	WorkStarts *time.Time
	WorkEnds   *time.Time
	Rating     *float32
	Lon        float32
	Lat        float32
	Distance   float32
}

func (q *Queries) GetFilteredDrivers(ctx context.Context, arg GetFilteredDriversParams) ([]GetFilteredDriversRow, error) {
	rows, err := q.db.Query(ctx, getFilteredDrivers,
		arg.Lat,
		arg.Lon,
		arg.WorkStarts,
		arg.WorkEnds,
		arg.MinRating,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilteredDriversRow
	for rows.Next() {
		var i GetFilteredDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkStarts,
			&i.WorkEnds,
			&i.Rating,
			&i.Lon,
			&i.Lat,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
