// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: freely_available.sql

package sqlc

import (
	"context"
	"time"
)

const createFreelyAvailable = `-- name: CreateFreelyAvailable :exec
INSERT INTO tow_driver_freely_available (
	user_id,
	from_date,
	to_date,
	from_location,
	en_route_order,
	tariff_per_km,
	from_address
) VALUES (
	$1, $2, $3,
	ST_SetSRID(ST_MakePoint($7::REAL, $8::REAL), 4326),
	$4, $5, $6
)
`

type CreateFreelyAvailableParams struct {
	UserID       int64
	FromDate     time.Time
	ToDate       time.Time
	EnRouteOrder *bool
	TariffPerKm  *float32
	FromAddress  string
	FromLon      float32
	FromLat      float32
}

func (q *Queries) CreateFreelyAvailable(ctx context.Context, arg CreateFreelyAvailableParams) error {
	_, err := q.db.Exec(ctx, createFreelyAvailable,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.EnRouteOrder,
		arg.TariffPerKm,
		arg.FromAddress,
		arg.FromLon,
		arg.FromLat,
	)
	return err
}

const createFreelyAvailableLocation = `-- name: CreateFreelyAvailableLocation :exec
INSERT INTO tow_driver_freely_available_to_location_list (
	tow_driver,
	location,
	address
) VALUES (
	$1,
	ST_SetSRID(ST_MakePoint($3::REAL, $4::REAL), 4326),
	$2
)
`

type CreateFreelyAvailableLocationParams struct {
	TowDriver int64
	Address   string
	Lon       float32
	Lat       float32
}

func (q *Queries) CreateFreelyAvailableLocation(ctx context.Context, arg CreateFreelyAvailableLocationParams) error {
	_, err := q.db.Exec(ctx, createFreelyAvailableLocation,
		arg.TowDriver,
		arg.Address,
		arg.Lon,
		arg.Lat,
	)
	return err
}

const deleteFreelyAvailable = `-- name: DeleteFreelyAvailable :exec
DELETE FROM tow_driver_freely_available
WHERE user_id = $1
`

func (q *Queries) DeleteFreelyAvailable(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteFreelyAvailable, userID)
	return err
}

const deleteFreelyAvailableLocations = `-- name: DeleteFreelyAvailableLocations :exec
DELETE FROM tow_driver_freely_available_to_location_list
WHERE tow_driver = $1
`

func (q *Queries) DeleteFreelyAvailableLocations(ctx context.Context, towDriver int64) error {
	_, err := q.db.Exec(ctx, deleteFreelyAvailableLocations, towDriver)
	return err
}

const getFreelyAvailableByUserID = `-- name: GetFreelyAvailableByUserID :one
SELECT
	user_id,
	from_date,
	to_date,
	ST_X(from_location::geometry)::REAL as from_lon,
	ST_Y(from_location::geometry)::REAL as from_lat,
	en_route_order,
	tariff_per_km,
	from_address
FROM tow_driver_freely_available
WHERE user_id = $1
`

type GetFreelyAvailableByUserIDRow struct {
	UserID       int64
	FromDate     time.Time
	ToDate       time.Time
	FromLon      float32
	FromLat      float32
	EnRouteOrder *bool
	TariffPerKm  *float32
	FromAddress  string
}

func (q *Queries) GetFreelyAvailableByUserID(ctx context.Context, userID int64) (GetFreelyAvailableByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getFreelyAvailableByUserID, userID)
	var i GetFreelyAvailableByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.FromDate,
		&i.ToDate,
		&i.FromLon,
		&i.FromLat,
		&i.EnRouteOrder,
		&i.TariffPerKm,
		&i.FromAddress,
	)
	return i, err
}

const getFreelyAvailableDrivers = `-- name: GetFreelyAvailableDrivers :many
SELECT
	tfa.user_id,
	tfa.from_date,
	tfa.to_date,
	ST_X(tfa.from_location::geometry)::REAL as from_lon,
	ST_Y(tfa.from_location::geometry)::REAL as from_lat,
	tfa.en_route_order,
	tfa.tariff_per_km,
	tfa.from_address,
	d.name,
	d.rating,
	d.profile_image,
	st_distance(
		tfa.from_location,
		st_setsrid(st_makepoint($1::REAL, $2::REAL), 4326)::geometry
	)::real AS distance
FROM tow_driver_freely_available tfa
JOIN driver d ON tfa.user_id = d.user_id
WHERE
	tfa.from_date <= NOW() AND tfa.to_date >= NOW()
	AND ($3::BOOLEAN IS NULL OR tfa.en_route_order = $3)
	AND ($4::REAL IS NULL OR tfa.tariff_per_km >= $4)
	AND ($5::REAL IS NULL OR tfa.tariff_per_km <= $5)
ORDER BY distance
`

type GetFreelyAvailableDriversParams struct {
	UserLon      float32
	UserLat      float32
	EnRouteOrder *bool
	MinTariff    *float32
	MaxTariff    *float32
}

type GetFreelyAvailableDriversRow struct {
	UserID       int64
	FromDate     time.Time
	ToDate       time.Time
	FromLon      float32
	FromLat      float32
	EnRouteOrder *bool
	TariffPerKm  *float32
	FromAddress  string
	Name         string
	Rating       *float32
	ProfileImage *string
	Distance     float32
}

func (q *Queries) GetFreelyAvailableDrivers(ctx context.Context, arg GetFreelyAvailableDriversParams) ([]GetFreelyAvailableDriversRow, error) {
	rows, err := q.db.Query(ctx, getFreelyAvailableDrivers,
		arg.UserLon,
		arg.UserLat,
		arg.EnRouteOrder,
		arg.MinTariff,
		arg.MaxTariff,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFreelyAvailableDriversRow
	for rows.Next() {
		var i GetFreelyAvailableDriversRow
		if err := rows.Scan(
			&i.UserID,
			&i.FromDate,
			&i.ToDate,
			&i.FromLon,
			&i.FromLat,
			&i.EnRouteOrder,
			&i.TariffPerKm,
			&i.FromAddress,
			&i.Name,
			&i.Rating,
			&i.ProfileImage,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFreelyAvailableLocations = `-- name: GetFreelyAvailableLocations :many
SELECT
	id,
	tow_driver,
	ST_X(location::geometry)::REAL as lon,
	ST_Y(location::geometry)::REAL as lat,
	address
FROM tow_driver_freely_available_to_location_list
WHERE tow_driver = $1
ORDER BY id
`

type GetFreelyAvailableLocationsRow struct {
	ID        int64
	TowDriver int64
	Lon       float32
	Lat       float32
	Address   string
}

func (q *Queries) GetFreelyAvailableLocations(ctx context.Context, towDriver int64) ([]GetFreelyAvailableLocationsRow, error) {
	rows, err := q.db.Query(ctx, getFreelyAvailableLocations, towDriver)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFreelyAvailableLocationsRow
	for rows.Next() {
		var i GetFreelyAvailableLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TowDriver,
			&i.Lon,
			&i.Lat,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFreelyAvailable = `-- name: UpdateFreelyAvailable :exec
UPDATE tow_driver_freely_available
SET
	from_date = $2,
	to_date = $3,
	from_location = ST_SetSRID(ST_MakePoint($7::REAL, $8::REAL), 4326),
	en_route_order = $4,
	tariff_per_km = $5,
	from_address = $6
WHERE user_id = $1
`

type UpdateFreelyAvailableParams struct {
	UserID       int64
	FromDate     time.Time
	ToDate       time.Time
	EnRouteOrder *bool
	TariffPerKm  *float32
	FromAddress  string
	FromLon      float32
	FromLat      float32
}

func (q *Queries) UpdateFreelyAvailable(ctx context.Context, arg UpdateFreelyAvailableParams) error {
	_, err := q.db.Exec(ctx, updateFreelyAvailable,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.EnRouteOrder,
		arg.TariffPerKm,
		arg.FromAddress,
		arg.FromLon,
		arg.FromLat,
	)
	return err
}
