// Package notification provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package notification

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// SubscriptionRequest defines model for SubscriptionRequest.
type SubscriptionRequest struct {
	AuthSecret      string  `json:"authSecret"`
	DevicePublicKey string  `json:"devicePublicKey"`
	DeviceType      *string `json:"deviceType,omitempty"`
	Endpoint        string  `json:"endpoint"`
}

// UnsubscribeRequest defines model for UnsubscribeRequest.
type UnsubscribeRequest struct {
	Endpoint string `json:"endpoint"`
}

// VapidPublicKeyResponse defines model for VapidPublicKeyResponse.
type VapidPublicKeyResponse struct {
	PublicKey string `json:"publicKey"`
}

// SubscribeJSONRequestBody defines body for Subscribe for application/json ContentType.
type SubscribeJSONRequestBody = SubscriptionRequest

// UnsubscribeJSONRequestBody defines body for Unsubscribe for application/json ContentType.
type UnsubscribeJSONRequestBody = UnsubscribeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /notifications/subscribe)
	Subscribe(c *gin.Context)

	// (POST /notifications/unsubscribe)
	Unsubscribe(c *gin.Context)

	// (GET /notifications/vapid-public-key)
	GetVapidPublicKey(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Subscribe operation middleware
func (siw *ServerInterfaceWrapper) Subscribe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Subscribe(c)
}

// Unsubscribe operation middleware
func (siw *ServerInterfaceWrapper) Unsubscribe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Unsubscribe(c)
}

// GetVapidPublicKey operation middleware
func (siw *ServerInterfaceWrapper) GetVapidPublicKey(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVapidPublicKey(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/notifications/subscribe", wrapper.Subscribe)
	router.POST(options.BaseURL+"/notifications/unsubscribe", wrapper.Unsubscribe)
	router.GET(options.BaseURL+"/notifications/vapid-public-key", wrapper.GetVapidPublicKey)
}

type SubscribeRequestObject struct {
	Body *SubscribeJSONRequestBody
}

type SubscribeResponseObject interface {
	VisitSubscribeResponse(w http.ResponseWriter) error
}

type Subscribe200Response struct {
}

func (response Subscribe200Response) VisitSubscribeResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UnsubscribeRequestObject struct {
	Body *UnsubscribeJSONRequestBody
}

type UnsubscribeResponseObject interface {
	VisitUnsubscribeResponse(w http.ResponseWriter) error
}

type Unsubscribe200Response struct {
}

func (response Unsubscribe200Response) VisitUnsubscribeResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetVapidPublicKeyRequestObject struct {
}

type GetVapidPublicKeyResponseObject interface {
	VisitGetVapidPublicKeyResponse(w http.ResponseWriter) error
}

type GetVapidPublicKey200JSONResponse VapidPublicKeyResponse

func (response GetVapidPublicKey200JSONResponse) VisitGetVapidPublicKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /notifications/subscribe)
	Subscribe(ctx context.Context, request SubscribeRequestObject) (SubscribeResponseObject, error)

	// (POST /notifications/unsubscribe)
	Unsubscribe(ctx context.Context, request UnsubscribeRequestObject) (UnsubscribeResponseObject, error)

	// (GET /notifications/vapid-public-key)
	GetVapidPublicKey(ctx context.Context, request GetVapidPublicKeyRequestObject) (GetVapidPublicKeyResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Subscribe operation middleware
func (sh *strictHandler) Subscribe(ctx *gin.Context) {
	var request SubscribeRequestObject

	var body SubscribeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Subscribe(ctx, request.(SubscribeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Subscribe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SubscribeResponseObject); ok {
		if err := validResponse.VisitSubscribeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Unsubscribe operation middleware
func (sh *strictHandler) Unsubscribe(ctx *gin.Context) {
	var request UnsubscribeRequestObject

	var body UnsubscribeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Unsubscribe(ctx, request.(UnsubscribeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Unsubscribe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UnsubscribeResponseObject); ok {
		if err := validResponse.VisitUnsubscribeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVapidPublicKey operation middleware
func (sh *strictHandler) GetVapidPublicKey(ctx *gin.Context) {
	var request GetVapidPublicKeyRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVapidPublicKey(ctx, request.(GetVapidPublicKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVapidPublicKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetVapidPublicKeyResponseObject); ok {
		if err := validResponse.VisitGetVapidPublicKeyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
