// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package sqlc

import (
	"context"
)

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deleteSubscription, endpoint)
	return err
}

const getSubscriptionsByUserID = `-- name: GetSubscriptionsByUserID :many
SELECT id, user_id, endpoint, device_public_key, auth_secret, device_type, created_at
FROM push_subscriptions
WHERE user_id = $1
`

func (q *Queries) GetSubscriptionsByUserID(ctx context.Context, userID int64) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.DevicePublicKey,
			&i.AuthSecret,
			&i.DeviceType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, device_public_key, auth_secret, device_type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, endpoint)
DO UPDATE SET
    device_public_key = EXCLUDED.device_public_key,
    auth_secret = EXCLUDED.auth_secret,
    device_type = EXCLUDED.device_type,
    created_at = CURRENT_TIMESTAMP
`

type UpsertSubscriptionParams struct {
	UserID          int64
	Endpoint        string
	DevicePublicKey string
	AuthSecret      string
	DeviceType      string
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.DevicePublicKey,
		arg.AuthSecret,
		arg.DeviceType,
	)
	return err
}
