// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID        pgtype.UUID
	SessionID int64
	TokenHash string
	ExpiresAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
}

type Driver struct {
	ID          int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	WorkStarts  pgtype.Time
	WorkEnds    pgtype.Time
	IsAvailable pgtype.Bool
	LastSeen    pgtype.Timestamptz
	Location    interface{}
	H3Res5      interface{}
	H3Res6      interface{}
	H3Res7      interface{}
	Rating      pgtype.Float4
}

type DriverRealtime struct {
	DriverID            int64
	UpdatedAt           pgtype.Timestamp
	RealtimeLocation    interface{}
	AverageSpeed        pgtype.Float4
	PredictedBearing    pgtype.Float4
	CoarseH3            interface{}
	DestinationLocation interface{}
	DestinationTime     pgtype.Timestamp
}

type Role struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Session struct {
	ID        pgtype.UUID
	UserID    int64
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
	IpAdress  *netip.Addr
	UserAgent pgtype.Text
}

type User struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserRole struct {
	UserID     int64
	RoleID     int32
	AssignedAt pgtype.Timestamp
}
