// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_repository.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_token(session_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateAccessTokenParams struct {
	SessionID int64
	TokenHash string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAccessToken, arg.SessionID, arg.TokenHash, arg.ExpiresAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO session(user_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateSession(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, createSession, userID)
	return err
}

const getSessionIDByTokenHash = `-- name: GetSessionIDByTokenHash :one
SELECT session_id from access_token
WHERE token_hash = $1
`

func (q *Queries) GetSessionIDByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionIDByTokenHash, tokenHash)
	var session_id int64
	err := row.Scan(&session_id)
	return session_id, err
}
