// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const validateToken = `-- name: ValidateToken :many
SELECT
	s.user_id,
	s.id AS session_id
FROM access_token AS at
JOIN session AS s ON s.id = sr.session_id
WHERE token_hash = $1
	AND at.expires_at > NOW()
	AND at.revoked_at IS NULL
`

type ValidateTokenRow struct {
	UserID    int64
	SessionID pgtype.UUID
}

func (q *Queries) ValidateToken(ctx context.Context, tokenHash string) ([]ValidateTokenRow, error) {
	rows, err := q.db.Query(ctx, validateToken, tokenHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidateTokenRow
	for rows.Next() {
		var i ValidateTokenRow
		if err := rows.Scan(&i.UserID, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
