// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_repository.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user"
DEFAULT VALUES
RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, createUser)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserRolesByID = `-- name: GetUserRolesByID :many
SELECT role_id
FROM user_roles
WHERE user_id = $1
`

func (q *Queries) GetUserRolesByID(ctx context.Context, userID int64) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUserRolesByID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var role_id int32
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
