// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// FindNearbyDriversParams defines parameters for FindNearbyDrivers.
type FindNearbyDriversParams struct {
	// Lat Latitude (WGS84) of the search center
	Lat float32 `form:"lat" json:"lat"`

	// Lon Longitude (WGS84) of the search center
	Lon float32 `form:"lon" json:"lon"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Find drivers within a specified radius of a point
	// (GET /geolocation/nearby)
	FindNearbyDrivers(c *gin.Context, params FindNearbyDriversParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// FindNearbyDrivers operation middleware
func (siw *ServerInterfaceWrapper) FindNearbyDrivers(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FindNearbyDriversParams

	// ------------- Required query parameter "lat" -------------

	if paramValue := c.Query("lat"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument lat is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "lat", c.Request.URL.Query(), &params.Lat)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lat: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "lon" -------------

	if paramValue := c.Query("lon"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument lon is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "lon", c.Request.URL.Query(), &params.Lon)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lon: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FindNearbyDrivers(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/geolocation/nearby", wrapper.FindNearbyDrivers)
}

type FindNearbyDriversRequestObject struct {
	Params FindNearbyDriversParams
}

type FindNearbyDriversResponseObject interface {
	VisitFindNearbyDriversResponse(w http.ResponseWriter) error
}

type FindNearbyDrivers200JSONResponse []struct {
	// DistanceMeters Distance from the search point in meters
	DistanceMeters int `json:"distance_meters"`

	// DriverId Unique identifier of the driver
	DriverId int `json:"driver_id"`
}

func (response FindNearbyDrivers200JSONResponse) VisitFindNearbyDriversResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindNearbyDrivers400Response struct {
}

func (response FindNearbyDrivers400Response) VisitFindNearbyDriversResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type FindNearbyDrivers500Response struct {
}

func (response FindNearbyDrivers500Response) VisitFindNearbyDriversResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Find drivers within a specified radius of a point
	// (GET /geolocation/nearby)
	FindNearbyDrivers(ctx context.Context, request FindNearbyDriversRequestObject) (FindNearbyDriversResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// FindNearbyDrivers operation middleware
func (sh *strictHandler) FindNearbyDrivers(ctx *gin.Context, params FindNearbyDriversParams) {
	var request FindNearbyDriversRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FindNearbyDrivers(ctx, request.(FindNearbyDriversRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindNearbyDrivers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(FindNearbyDriversResponseObject); ok {
		if err := validResponse.VisitFindNearbyDriversResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
