// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// MovingDriver defines model for MovingDriver.
type MovingDriver struct {
	DriverId   int         `json:"driver_id"`
	Lat        float32     `json:"lat"`
	Lon        float32     `json:"lon"`
	PathMeters int         `json:"path_meters"`
	Points     [][]float32 `json:"points"`
	TravelTime float32     `json:"travel_time"`
}

// GetMovingDriversByIDsJSONBody defines parameters for GetMovingDriversByIDs.
type GetMovingDriversByIDsJSONBody struct {
	Ids []int `json:"ids"`
}

// GetClosestWithinRadiusMovingDriversByIDsParams defines parameters for GetClosestWithinRadiusMovingDriversByIDs.
type GetClosestWithinRadiusMovingDriversByIDsParams struct {
	Lat          float32 `form:"lat" json:"lat"`
	Lon          float32 `form:"lon" json:"lon"`
	RadiusMeters int     `form:"radius_meters" json:"radius_meters"`
}

// GetMovingDriversByIDsJSONRequestBody defines body for GetMovingDriversByIDs for application/json ContentType.
type GetMovingDriversByIDsJSONRequestBody GetMovingDriversByIDsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /drivers/moving)
	GetMovingDriversByIDs(c *gin.Context)

	// (GET /drivers/moving/closest)
	GetClosestWithinRadiusMovingDriversByIDs(c *gin.Context, params GetClosestWithinRadiusMovingDriversByIDsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMovingDriversByIDs operation middleware
func (siw *ServerInterfaceWrapper) GetMovingDriversByIDs(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMovingDriversByIDs(c)
}

// GetClosestWithinRadiusMovingDriversByIDs operation middleware
func (siw *ServerInterfaceWrapper) GetClosestWithinRadiusMovingDriversByIDs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClosestWithinRadiusMovingDriversByIDsParams

	// ------------- Required query parameter "lat" -------------

	if paramValue := c.Query("lat"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument lat is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "lat", c.Request.URL.Query(), &params.Lat)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lat: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "lon" -------------

	if paramValue := c.Query("lon"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument lon is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "lon", c.Request.URL.Query(), &params.Lon)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter lon: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "radius_meters" -------------

	if paramValue := c.Query("radius_meters"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument radius_meters is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "radius_meters", c.Request.URL.Query(), &params.RadiusMeters)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter radius_meters: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClosestWithinRadiusMovingDriversByIDs(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/drivers/moving", wrapper.GetMovingDriversByIDs)
	router.GET(options.BaseURL+"/drivers/moving/closest", wrapper.GetClosestWithinRadiusMovingDriversByIDs)
}

type GetMovingDriversByIDsRequestObject struct {
	Body *GetMovingDriversByIDsJSONRequestBody
}

type GetMovingDriversByIDsResponseObject interface {
	VisitGetMovingDriversByIDsResponse(w http.ResponseWriter) error
}

type GetMovingDriversByIDs200JSONResponse []MovingDriver

func (response GetMovingDriversByIDs200JSONResponse) VisitGetMovingDriversByIDsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMovingDriversByIDs400Response struct {
}

func (response GetMovingDriversByIDs400Response) VisitGetMovingDriversByIDsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetMovingDriversByIDs500Response struct {
}

func (response GetMovingDriversByIDs500Response) VisitGetMovingDriversByIDsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetClosestWithinRadiusMovingDriversByIDsRequestObject struct {
	Params GetClosestWithinRadiusMovingDriversByIDsParams
}

type GetClosestWithinRadiusMovingDriversByIDsResponseObject interface {
	VisitGetClosestWithinRadiusMovingDriversByIDsResponse(w http.ResponseWriter) error
}

type GetClosestWithinRadiusMovingDriversByIDs200JSONResponse []MovingDriver

func (response GetClosestWithinRadiusMovingDriversByIDs200JSONResponse) VisitGetClosestWithinRadiusMovingDriversByIDsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClosestWithinRadiusMovingDriversByIDs400Response struct {
}

func (response GetClosestWithinRadiusMovingDriversByIDs400Response) VisitGetClosestWithinRadiusMovingDriversByIDsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetClosestWithinRadiusMovingDriversByIDs500Response struct {
}

func (response GetClosestWithinRadiusMovingDriversByIDs500Response) VisitGetClosestWithinRadiusMovingDriversByIDsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /drivers/moving)
	GetMovingDriversByIDs(ctx context.Context, request GetMovingDriversByIDsRequestObject) (GetMovingDriversByIDsResponseObject, error)

	// (GET /drivers/moving/closest)
	GetClosestWithinRadiusMovingDriversByIDs(ctx context.Context, request GetClosestWithinRadiusMovingDriversByIDsRequestObject) (GetClosestWithinRadiusMovingDriversByIDsResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetMovingDriversByIDs operation middleware
func (sh *strictHandler) GetMovingDriversByIDs(ctx *gin.Context) {
	var request GetMovingDriversByIDsRequestObject

	var body GetMovingDriversByIDsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMovingDriversByIDs(ctx, request.(GetMovingDriversByIDsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMovingDriversByIDs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetMovingDriversByIDsResponseObject); ok {
		if err := validResponse.VisitGetMovingDriversByIDsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetClosestWithinRadiusMovingDriversByIDs operation middleware
func (sh *strictHandler) GetClosestWithinRadiusMovingDriversByIDs(ctx *gin.Context, params GetClosestWithinRadiusMovingDriversByIDsParams) {
	var request GetClosestWithinRadiusMovingDriversByIDsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetClosestWithinRadiusMovingDriversByIDs(ctx, request.(GetClosestWithinRadiusMovingDriversByIDsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClosestWithinRadiusMovingDriversByIDs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetClosestWithinRadiusMovingDriversByIDsResponseObject); ok {
		if err := validResponse.VisitGetClosestWithinRadiusMovingDriversByIDsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
