// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDriver = `-- name: CreateDriver :one
INSERT INTO
	driver (
		work_starts,
		work_ends,
		location,
		rating
	) VALUES ($1, $2, ST_SetSRID(ST_MakePoint($3::REAL, $4::REAL), 4326), $5)
RETURNING id
`

type CreateDriverParams struct {
	WorkStarts pgtype.Time
	WorkEnds   pgtype.Time
	Column3    float32
	Column4    float32
	Rating     pgtype.Float4
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (uint32, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.WorkStarts,
		arg.WorkEnds,
		arg.Column3,
		arg.Column4,
		arg.Rating,
	)
	var id uint32
	err := row.Scan(&id)
	return id, err
}

const getDriverByID = `-- name: GetDriverByID :one
SELECT
	id,
	work_starts,
	work_ends,
	rating,
	ST_X(location::geometry)::REAL as lon,
	ST_Y(location::geometry)::REAL as lat
FROM driver
WHERE id = $1
`

type GetDriverByIDRow struct {
	ID         uint32
	WorkStarts pgtype.Time
	WorkEnds   pgtype.Time
	Rating     pgtype.Float4
	Lon        float32
	Lat        float32
}

func (q *Queries) GetDriverByID(ctx context.Context, id uint32) (GetDriverByIDRow, error) {
	row := q.db.QueryRow(ctx, getDriverByID, id)
	var i GetDriverByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkStarts,
		&i.WorkEnds,
		&i.Rating,
		&i.Lon,
		&i.Lat,
	)
	return i, err
}
