// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter_drivers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFilteredDrivers = `-- name: GetFilteredDrivers :many
SELECT 
	id,
	work_starts, 
	work_ends, 
	rating, 
	location::text,
	st_distance(location, st_setsrid(st_makepoint($1::real, $2::real), 4326)::geometry)::real AS distance
FROM driver
WHERE 
	($3::text IS NULL OR work_starts >= $3::time) AND
	($4::text IS NULL OR work_ends <= $4::time) AND
	($5::real IS NULL OR rating >= $5)
ORDER BY distance
`

type GetFilteredDriversParams struct {
	Column1 float32
	Column2 float32
	Column3 string
	Column4 string
	Column5 float32
}

type GetFilteredDriversRow struct {
	ID         uint32
	WorkStarts pgtype.Time
	WorkEnds   pgtype.Time
	Rating     pgtype.Float4
	Location   string
	Distance   float32
}

func (q *Queries) GetFilteredDrivers(ctx context.Context, arg GetFilteredDriversParams) ([]GetFilteredDriversRow, error) {
	rows, err := q.db.Query(ctx, getFilteredDrivers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilteredDriversRow
	for rows.Next() {
		var i GetFilteredDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkStarts,
			&i.WorkEnds,
			&i.Rating,
			&i.Location,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
