// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_filtered_drivers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFilteredDrivers = `-- name: GetFilteredDrivers :many
SELECT 
    id,
	name,
    work_starts, 
    work_ends, 
    rating, 
	ST_X(location::GEOMETRY)::REAL AS lon,
	ST_Y(location::GEOMETRY)::REAL AS lat,
    st_distance(
        location, 
        st_setsrid(
            st_makepoint($1::REAL, $2::REAL), 
            4326
        )::geometry
    )::real AS distance
FROM driver
WHERE 
    ($3::TIME IS NULL OR work_starts <= $3)
    AND ($4::TIME IS NULL OR work_ends >= $4)
    AND ($5::REAL IS NULL OR rating >= $5)
ORDER BY distance
`

type GetFilteredDriversParams struct {
	Lat        float32
	Lon        float32
	WorkStarts pgtype.Time
	WorkEnds   pgtype.Time
	MinRating  pgtype.Float4
}

type GetFilteredDriversRow struct {
	ID         uint32
	Name       string
	WorkStarts pgtype.Time
	WorkEnds   pgtype.Time
	Rating     pgtype.Float4
	Lon        float32
	Lat        float32
	Distance   float32
}

func (q *Queries) GetFilteredDrivers(ctx context.Context, arg GetFilteredDriversParams) ([]GetFilteredDriversRow, error) {
	rows, err := q.db.Query(ctx, getFilteredDrivers,
		arg.Lat,
		arg.Lon,
		arg.WorkStarts,
		arg.WorkEnds,
		arg.MinRating,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilteredDriversRow
	for rows.Next() {
		var i GetFilteredDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkStarts,
			&i.WorkEnds,
			&i.Rating,
			&i.Lon,
			&i.Lat,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
