// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type City struct {
	ID         int32
	Name       string
	StateID    pgtype.Int4
	Geometry   interface{}
	Bbox       interface{}
	H3Res9     []interface{}
	Population pgtype.Int4
	Timezone   pgtype.Text
	CreatedAt  pgtype.Timestamp
}

type CountryAdministrativeBoundary struct {
	ID         int32
	Name       string
	AdminLevel pgtype.Int4
	Geometry   interface{}
}

type Driver struct {
	ID          uint32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	WorkStarts  pgtype.Time
	WorkEnds    pgtype.Time
	Rating      pgtype.Float4
	IsAvailable pgtype.Bool
	LastSeen    pgtype.Timestamptz
	Location    interface{}
	H3Res8      interface{}
	H3Res9      interface{}
	H3Res10     interface{}
}

type DriverRealtime struct {
	DriverID          int64
	RealtimeLocation  interface{}
	RealtimeUpdatedAt pgtype.Timestamp
	RealtimeSpeed     pgtype.Float4
	RealtimeBearing   pgtype.Float4
}

type OrderScheduled struct {
	DriverID            int64
	DestinationLocation interface{}
	DestinationTime     pgtype.Timestamptz
	IsIntercity         pgtype.Bool
}

type State struct {
	ID        int32
	Name      string
	IsoCode   pgtype.Text
	Geometry  interface{}
	Bbox      interface{}
	H3Res8    []interface{}
	CreatedAt pgtype.Timestamp
}
