// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Driver struct {
	ID                 uint32
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	Name               string
	ProfilePicturePath pgtype.Text
	WorkStarts         pgtype.Time
	WorkEnds           pgtype.Time
	IsAvailable        pgtype.Bool
	LastSeen           pgtype.Timestamptz
	Location           interface{}
	CityID             pgtype.Int4
	StateID            pgtype.Int4
	Rating             pgtype.Float4
}
