// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlc

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order" (
	customer_id,
	from_location,
	to_location,
	from_address,
	to_address,
	total_distance_meters,
	how_many_wheels_blocked,
	price_rubles,
	car_weight_kg,
	car_length_meters,
	car_type,
	car_name,
	car_photo_url,
	customer_message,
	status
) VALUES (
	$1,
	ST_SetSRID(ST_MakePoint($9::REAL, $10::REAL), 4326),
	ST_SetSRID(ST_MakePoint($11::REAL, $12::REAL), 4326),
	$13,
	$14,
	$2,
	$3,
	$4,
	$5,
	$6,
	$15::CAR_TYPE,
	$16,
	$7,
	$8,
	'forming'
)
RETURNING id
`

type CreateOrderParams struct {
	CustomerID           int64
	TotalDistanceMeters  *int32
	HowManyWheelsBlocked int16
	PriceRubles          *int32
	CarWeightKg          int32
	CarLengthMeters      float32
	CarPhotoUrl          *string
	CustomerMessage      *string
	FromLon              float32
	FromLat              float32
	ToLon                float32
	ToLat                float32
	FromAddress          string
	ToAddress            string
	CarType              CarType
	CarName              string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CustomerID,
		arg.TotalDistanceMeters,
		arg.HowManyWheelsBlocked,
		arg.PriceRubles,
		arg.CarWeightKg,
		arg.CarLengthMeters,
		arg.CarPhotoUrl,
		arg.CustomerMessage,
		arg.FromLon,
		arg.FromLat,
		arg.ToLon,
		arg.ToLat,
		arg.FromAddress,
		arg.ToAddress,
		arg.CarType,
		arg.CarName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteActiveOrder = `-- name: DeleteActiveOrder :exec
DELETE FROM "order"
WHERE customer_id = $1 AND status IN ('forming', 'pending')
`

func (q *Queries) DeleteActiveOrder(ctx context.Context, customerID int64) error {
	_, err := q.db.Exec(ctx, deleteActiveOrder, customerID)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
	id,
	created_at,
	updated_at,
	customer_id,
	driver_id,
	ST_X(from_location::geometry)::REAL AS from_lon,
	ST_Y(from_location::geometry)::REAL AS from_lat,
	ST_X(to_location::geometry)::REAL AS to_lon,
	ST_Y(to_location::geometry)::REAL AS to_lat,
	from_address,
	to_address,
	total_distance_meters,
	how_many_wheels_blocked,
	price_rubles,
	car_weight_kg,
	car_length_meters,
	car_type,
	car_name,
	car_photo_url,
	customer_message,
	status,
	accepted_at,
	picked_up_at,
	completed_at,
	cancelled_at,
	cancellation_reason
FROM "order"
WHERE id = $1
`

type GetOrderByIDRow struct {
	ID                   int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CustomerID           int64
	DriverID             *int64
	FromLon              float32
	FromLat              float32
	ToLon                float32
	ToLat                float32
	FromAddress          string
	ToAddress            string
	TotalDistanceMeters  *int32
	HowManyWheelsBlocked int16
	PriceRubles          *int32
	CarWeightKg          int32
	CarLengthMeters      float32
	CarType              CarType
	CarName              string
	CarPhotoUrl          *string
	CustomerMessage      *string
	Status               OrderStatus
	AcceptedAt           *time.Time
	PickedUpAt           *time.Time
	CompletedAt          *time.Time
	CancelledAt          *time.Time
	CancellationReason   *string
}

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.DriverID,
		&i.FromLon,
		&i.FromLat,
		&i.ToLon,
		&i.ToLat,
		&i.FromAddress,
		&i.ToAddress,
		&i.TotalDistanceMeters,
		&i.HowManyWheelsBlocked,
		&i.PriceRubles,
		&i.CarWeightKg,
		&i.CarLengthMeters,
		&i.CarType,
		&i.CarName,
		&i.CarPhotoUrl,
		&i.CustomerMessage,
		&i.Status,
		&i.AcceptedAt,
		&i.PickedUpAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
	)
	return i, err
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT
	id,
	created_at,
	updated_at,
	customer_id,
	driver_id,
	ST_X(from_location::geometry)::REAL AS from_lon,
	ST_Y(from_location::geometry)::REAL AS from_lat,
	ST_X(to_location::geometry)::REAL AS to_lon,
	ST_Y(to_location::geometry)::REAL AS to_lat,
	from_address,
	to_address,
	total_distance_meters,
	how_many_wheels_blocked,
	price_rubles,
	car_weight_kg,
	car_length_meters,
	car_type,
	car_name,
	car_photo_url,
	customer_message,
	status,
	accepted_at,
	picked_up_at,
	completed_at,
	cancelled_at,
	cancellation_reason
FROM "order"
WHERE customer_id = $1
ORDER BY created_at DESC
`

type ListOrdersByCustomerRow struct {
	ID                   int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CustomerID           int64
	DriverID             *int64
	FromLon              float32
	FromLat              float32
	ToLon                float32
	ToLat                float32
	FromAddress          string
	ToAddress            string
	TotalDistanceMeters  *int32
	HowManyWheelsBlocked int16
	PriceRubles          *int32
	CarWeightKg          int32
	CarLengthMeters      float32
	CarType              CarType
	CarName              string
	CarPhotoUrl          *string
	CustomerMessage      *string
	Status               OrderStatus
	AcceptedAt           *time.Time
	PickedUpAt           *time.Time
	CompletedAt          *time.Time
	CancelledAt          *time.Time
	CancellationReason   *string
}

func (q *Queries) ListOrdersByCustomer(ctx context.Context, customerID int64) ([]ListOrdersByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByCustomerRow
	for rows.Next() {
		var i ListOrdersByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.DriverID,
			&i.FromLon,
			&i.FromLat,
			&i.ToLon,
			&i.ToLat,
			&i.FromAddress,
			&i.ToAddress,
			&i.TotalDistanceMeters,
			&i.HowManyWheelsBlocked,
			&i.PriceRubles,
			&i.CarWeightKg,
			&i.CarLengthMeters,
			&i.CarType,
			&i.CarName,
			&i.CarPhotoUrl,
			&i.CustomerMessage,
			&i.Status,
			&i.AcceptedAt,
			&i.PickedUpAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancellationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByDriver = `-- name: ListOrdersByDriver :many
SELECT
	id,
	created_at,
	updated_at,
	customer_id,
	driver_id,
	ST_X(from_location::geometry)::REAL AS from_lon,
	ST_Y(from_location::geometry)::REAL AS from_lat,
	ST_X(to_location::geometry)::REAL AS to_lon,
	ST_Y(to_location::geometry)::REAL AS to_lat,
	from_address,
	to_address,
	total_distance_meters,
	how_many_wheels_blocked,
	price_rubles,
	car_weight_kg,
	car_length_meters,
	car_type,
	car_name,
	car_photo_url,
	customer_message,
	status,
	accepted_at,
	picked_up_at,
	completed_at,
	cancelled_at,
	cancellation_reason
FROM "order"
WHERE driver_id = $1
ORDER BY created_at DESC
`

type ListOrdersByDriverRow struct {
	ID                   int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CustomerID           int64
	DriverID             *int64
	FromLon              float32
	FromLat              float32
	ToLon                float32
	ToLat                float32
	FromAddress          string
	ToAddress            string
	TotalDistanceMeters  *int32
	HowManyWheelsBlocked int16
	PriceRubles          *int32
	CarWeightKg          int32
	CarLengthMeters      float32
	CarType              CarType
	CarName              string
	CarPhotoUrl          *string
	CustomerMessage      *string
	Status               OrderStatus
	AcceptedAt           *time.Time
	PickedUpAt           *time.Time
	CompletedAt          *time.Time
	CancelledAt          *time.Time
	CancellationReason   *string
}

func (q *Queries) ListOrdersByDriver(ctx context.Context, driverID *int64) ([]ListOrdersByDriverRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByDriver, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByDriverRow
	for rows.Next() {
		var i ListOrdersByDriverRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.DriverID,
			&i.FromLon,
			&i.FromLat,
			&i.ToLon,
			&i.ToLat,
			&i.FromAddress,
			&i.ToAddress,
			&i.TotalDistanceMeters,
			&i.HowManyWheelsBlocked,
			&i.PriceRubles,
			&i.CarWeightKg,
			&i.CarLengthMeters,
			&i.CarType,
			&i.CarName,
			&i.CarPhotoUrl,
			&i.CustomerMessage,
			&i.Status,
			&i.AcceptedAt,
			&i.PickedUpAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancellationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderDriver = `-- name: SetOrderDriver :exec
UPDATE "order"
SET driver_id = $2, status = 'accepted'
WHERE id = $1 AND status = 'pending'
`

type SetOrderDriverParams struct {
	ID       int64
	DriverID *int64
}

func (q *Queries) SetOrderDriver(ctx context.Context, arg SetOrderDriverParams) error {
	_, err := q.db.Exec(ctx, setOrderDriver, arg.ID, arg.DriverID)
	return err
}

const updateOrderDetails = `-- name: UpdateOrderDetails :one
UPDATE "order"
SET
	from_location = ST_SetSRID(ST_MakePoint($9::REAL, $10::REAL), 4326),
	to_location = ST_SetSRID(ST_MakePoint($11::REAL, $12::REAL), 4326),
	from_address = $13,
	to_address = $14,
	total_distance_meters = $2,
	how_many_wheels_blocked = $3,
	price_rubles = $4,
	car_weight_kg = $5,
	car_length_meters = $6,
	car_type = $15::CAR_TYPE,
	car_name = $16,
	car_photo_url = $7,
	customer_message = $8,
	updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING
	id,
	created_at,
	updated_at,
	customer_id,
	driver_id,
	ST_X(from_location::geometry)::REAL AS from_lon,
	ST_Y(from_location::geometry)::REAL AS from_lat,
	ST_X(to_location::geometry)::REAL AS to_lon,
	ST_Y(to_location::geometry)::REAL AS to_lat,
	from_address,
	to_address,
	total_distance_meters,
	how_many_wheels_blocked,
	price_rubles,
	car_weight_kg,
	car_length_meters,
	car_type,
	car_name,
	car_photo_url,
	customer_message,
	status,
	accepted_at,
	picked_up_at,
	completed_at,
	cancelled_at,
	cancellation_reason
`

type UpdateOrderDetailsParams struct {
	ID                   int64
	TotalDistanceMeters  *int32
	HowManyWheelsBlocked int16
	PriceRubles          *int32
	CarWeightKg          int32
	CarLengthMeters      float32
	CarPhotoUrl          *string
	CustomerMessage      *string
	FromLon              float32
	FromLat              float32
	ToLon                float32
	ToLat                float32
	FromAddress          string
	ToAddress            string
	CarType              CarType
	CarName              string
}

type UpdateOrderDetailsRow struct {
	ID                   int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CustomerID           int64
	DriverID             *int64
	FromLon              float32
	FromLat              float32
	ToLon                float32
	ToLat                float32
	FromAddress          string
	ToAddress            string
	TotalDistanceMeters  *int32
	HowManyWheelsBlocked int16
	PriceRubles          *int32
	CarWeightKg          int32
	CarLengthMeters      float32
	CarType              CarType
	CarName              string
	CarPhotoUrl          *string
	CustomerMessage      *string
	Status               OrderStatus
	AcceptedAt           *time.Time
	PickedUpAt           *time.Time
	CompletedAt          *time.Time
	CancelledAt          *time.Time
	CancellationReason   *string
}

func (q *Queries) UpdateOrderDetails(ctx context.Context, arg UpdateOrderDetailsParams) (UpdateOrderDetailsRow, error) {
	row := q.db.QueryRow(ctx, updateOrderDetails,
		arg.ID,
		arg.TotalDistanceMeters,
		arg.HowManyWheelsBlocked,
		arg.PriceRubles,
		arg.CarWeightKg,
		arg.CarLengthMeters,
		arg.CarPhotoUrl,
		arg.CustomerMessage,
		arg.FromLon,
		arg.FromLat,
		arg.ToLon,
		arg.ToLat,
		arg.FromAddress,
		arg.ToAddress,
		arg.CarType,
		arg.CarName,
	)
	var i UpdateOrderDetailsRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.DriverID,
		&i.FromLon,
		&i.FromLat,
		&i.ToLon,
		&i.ToLat,
		&i.FromAddress,
		&i.ToAddress,
		&i.TotalDistanceMeters,
		&i.HowManyWheelsBlocked,
		&i.PriceRubles,
		&i.CarWeightKg,
		&i.CarLengthMeters,
		&i.CarType,
		&i.CarName,
		&i.CarPhotoUrl,
		&i.CustomerMessage,
		&i.Status,
		&i.AcceptedAt,
		&i.PickedUpAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE "order"
SET
	status = $2,
	accepted_at = COALESCE($3::TIMESTAMP, accepted_at),
	picked_up_at = COALESCE($4::TIMESTAMP, picked_up_at),
	completed_at = COALESCE($5::TIMESTAMP, completed_at),
	cancelled_at = COALESCE($6::TIMESTAMP, cancelled_at),
	cancellation_reason = COALESCE($7, cancellation_reason)
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID                 int64
	Status             OrderStatus
	AcceptedAt         *time.Time
	PickedUpAt         *time.Time
	CompletedAt        *time.Time
	CancelledAt        *time.Time
	CancellationReason *string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus,
		arg.ID,
		arg.Status,
		arg.AcceptedAt,
		arg.PickedUpAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.CancellationReason,
	)
	return err
}
