services:
  photon:
    image: ghcr.io/rtuszik/photon-docker:latest
    container_name: geoproj-photon
    environment:
      - UPDATE_STRATEGY=PARALLEL
      - UPDATE_INTERVAL=30d
      - LOG_LEVEL=DEBUG # Options: DEBUG, INFO, ERROR
      # - BASE_URL=https://r2.koalasec.org/public
      # - BASE_URL=https://download1.graphhopper.com/public/
      - REGION=ru
    volumes:
      - ./data:/photon/data
    restart: unless-stopped
    ports:
      - "2322:2322"
    networks:
      - geoproj-network

networks:
  geoproj-network:
    external: true
