// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// Driver defines model for Driver.
type Driver struct {
	Id         int32      `json:"id"`
	Lat        float32    `json:"lat"`
	Lon        float32    `json:"lon"`
	Name       string     `json:"name"`
	Rating     *float32   `json:"rating,omitempty"`
	WorkEnds   *time.Time `json:"work_ends,omitempty"`
	WorkStarts *time.Time `json:"work_starts,omitempty"`
}

// CreateDriverJSONBody defines parameters for CreateDriver.
type CreateDriverJSONBody struct {
	// Lat Latitude (WGS84)
	Lat float32 `json:"lat"`

	// Lon Longitude (WGS84)
	Lon float32 `json:"lon"`

	// WorkEnds End of work time (ISO 8601)
	WorkEnds time.Time `json:"work_ends"`

	// WorkStarts Start of work time (ISO 8601)
	WorkStarts time.Time `json:"work_starts"`
}

// GetFilteredDriversJSONBody defines parameters for GetFilteredDrivers.
type GetFilteredDriversJSONBody struct {
	MinRating *float32 `json:"min_rating,omitempty"`

	// UserLat Latitude (WGS84)
	UserLat float32 `json:"user_lat"`

	// UserLon Longitude (WGS84)
	UserLon    float32 `json:"user_lon"`
	WorkEnds   *string `json:"work_ends,omitempty"`
	WorkStarts *string `json:"work_starts,omitempty"`
}

// CreateDriverJSONRequestBody defines body for CreateDriver for application/json ContentType.
type CreateDriverJSONRequestBody CreateDriverJSONBody

// GetFilteredDriversJSONRequestBody defines body for GetFilteredDrivers for application/json ContentType.
type GetFilteredDriversJSONRequestBody GetFilteredDriversJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /drivers)
	CreateDriver(c *gin.Context)

	// (GET /drivers/{id})
	GetDriverById(c *gin.Context, id int)

	// (POST /filer)
	GetFilteredDrivers(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateDriver operation middleware
func (siw *ServerInterfaceWrapper) CreateDriver(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDriver(c)
}

// GetDriverById operation middleware
func (siw *ServerInterfaceWrapper) GetDriverById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDriverById(c, id)
}

// GetFilteredDrivers operation middleware
func (siw *ServerInterfaceWrapper) GetFilteredDrivers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFilteredDrivers(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/drivers", wrapper.CreateDriver)
	router.GET(options.BaseURL+"/drivers/:id", wrapper.GetDriverById)
	router.POST(options.BaseURL+"/filer", wrapper.GetFilteredDrivers)
}

type CreateDriverRequestObject struct {
	Body *CreateDriverJSONRequestBody
}

type CreateDriverResponseObject interface {
	VisitCreateDriverResponse(w http.ResponseWriter) error
}

type CreateDriver201JSONResponse struct {
	// Id ID of the newly created driver
	Id int `json:"id"`
}

func (response CreateDriver201JSONResponse) VisitCreateDriverResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDriver400Response struct {
}

func (response CreateDriver400Response) VisitCreateDriverResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetDriverByIdRequestObject struct {
	Id int `json:"id"`
}

type GetDriverByIdResponseObject interface {
	VisitGetDriverByIdResponse(w http.ResponseWriter) error
}

type GetDriverById200JSONResponse struct {
	Id         int        `json:"id"`
	Lat        *float32   `json:"lat,omitempty"`
	Lon        *float32   `json:"lon,omitempty"`
	Rating     *float32   `json:"rating,omitempty"`
	WorkEnds   *time.Time `json:"work_ends,omitempty"`
	WorkStarts *time.Time `json:"work_starts,omitempty"`
}

func (response GetDriverById200JSONResponse) VisitGetDriverByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDriverById404Response struct {
}

func (response GetDriverById404Response) VisitGetDriverByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetFilteredDriversRequestObject struct {
	Body *GetFilteredDriversJSONRequestBody
}

type GetFilteredDriversResponseObject interface {
	VisitGetFilteredDriversResponse(w http.ResponseWriter) error
}

type GetFilteredDrivers200JSONResponse struct {
	Drivers *[]Driver `json:"drivers,omitempty"`
}

func (response GetFilteredDrivers200JSONResponse) VisitGetFilteredDriversResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFilteredDrivers404Response struct {
}

func (response GetFilteredDrivers404Response) VisitGetFilteredDriversResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /drivers)
	CreateDriver(ctx context.Context, request CreateDriverRequestObject) (CreateDriverResponseObject, error)

	// (GET /drivers/{id})
	GetDriverById(ctx context.Context, request GetDriverByIdRequestObject) (GetDriverByIdResponseObject, error)

	// (POST /filer)
	GetFilteredDrivers(ctx context.Context, request GetFilteredDriversRequestObject) (GetFilteredDriversResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateDriver operation middleware
func (sh *strictHandler) CreateDriver(ctx *gin.Context) {
	var request CreateDriverRequestObject

	var body CreateDriverJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDriver(ctx, request.(CreateDriverRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDriver")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateDriverResponseObject); ok {
		if err := validResponse.VisitCreateDriverResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDriverById operation middleware
func (sh *strictHandler) GetDriverById(ctx *gin.Context, id int) {
	var request GetDriverByIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDriverById(ctx, request.(GetDriverByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDriverById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetDriverByIdResponseObject); ok {
		if err := validResponse.VisitGetDriverByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFilteredDrivers operation middleware
func (sh *strictHandler) GetFilteredDrivers(ctx *gin.Context) {
	var request GetFilteredDriversRequestObject

	var body GetFilteredDriversJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetFilteredDrivers(ctx, request.(GetFilteredDriversRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFilteredDrivers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetFilteredDriversResponseObject); ok {
		if err := validResponse.VisitGetFilteredDriversResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
