// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Driver defines model for Driver.
type Driver struct {
	// Address Reverse-geocoded address of the driver's location
	Address     *string `json:"address,omitempty"`
	IsAvailable *bool   `json:"is_available,omitempty"`
	Lat         float32 `json:"lat"`
	Lon         float32 `json:"lon"`

	// MaxCarLengthMeters Maximum car length in meters for tow drivers
	MaxCarLengthMeters *float32 `json:"max_car_length_meters,omitempty"`

	// MaxCarWeightKg Maximum car weight in kg for tow drivers
	MaxCarWeightKg *int       `json:"max_car_weight_kg,omitempty"`
	Name           string     `json:"name"`
	Phone          *string    `json:"phone,omitempty"`
	ProfileImage   *string    `json:"profile_image,omitempty"`
	Rating         *float32   `json:"rating,omitempty"`
	UserId         int64      `json:"user_id"`
	WorkEnds       *time.Time `json:"work_ends,omitempty"`
	WorkStarts     *time.Time `json:"work_starts,omitempty"`
}

// DriverProfile defines model for DriverProfile.
type DriverProfile struct {
	// Lat Latitude (WGS84)
	Lat float32 `json:"lat"`

	// Lon Longitude (WGS84)
	Lon float32 `json:"lon"`

	// MaxCarLengthMeters Maximum car length in meters for tow drivers
	MaxCarLengthMeters *float32 `json:"max_car_length_meters,omitempty"`

	// MaxCarWeightKg Maximum car weight in kg for tow drivers
	MaxCarWeightKg *int `json:"max_car_weight_kg,omitempty"`

	// Name Driver's display name
	Name string `json:"name"`

	// Phone Driver phone number
	Phone *string `json:"phone,omitempty"`

	// WorkEnds End of work time (HH:MM:SS)
	WorkEnds *string `json:"work_ends,omitempty"`

	// WorkStarts Start of work time (HH:MM:SS)
	WorkStarts *string `json:"work_starts,omitempty"`
}

// GetFilteredDriversJSONBody defines parameters for GetFilteredDrivers.
type GetFilteredDriversJSONBody struct {
	MinRating *float32 `json:"min_rating,omitempty"`

	// UserLat Latitude (WGS84)
	UserLat float32 `json:"user_lat"`

	// UserLon Longitude (WGS84)
	UserLon    float32 `json:"user_lon"`
	WorkEnds   *string `json:"work_ends,omitempty"`
	WorkStarts *string `json:"work_starts,omitempty"`
}

// GetFilteredDriversJSONRequestBody defines body for GetFilteredDrivers for application/json ContentType.
type GetFilteredDriversJSONRequestBody GetFilteredDriversJSONBody

// CreateDriverProfileJSONRequestBody defines body for CreateDriverProfile for application/json ContentType.
type CreateDriverProfileJSONRequestBody = DriverProfile

// UpdateDriverProfileJSONRequestBody defines body for UpdateDriverProfile for application/json ContentType.
type UpdateDriverProfileJSONRequestBody = DriverProfile

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /driver/filter)
	GetFilteredDrivers(c *gin.Context)
	// Get my driver profile
	// (GET /driver/profile)
	GetMyDriverProfile(c *gin.Context)
	// Create driver profile
	// (POST /driver/profile)
	CreateDriverProfile(c *gin.Context)
	// Update driver profile
	// (PUT /driver/profile)
	UpdateDriverProfile(c *gin.Context)

	// (GET /driver/{user_id})
	GetDriverByUserId(c *gin.Context, userId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetFilteredDrivers operation middleware
func (siw *ServerInterfaceWrapper) GetFilteredDrivers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFilteredDrivers(c)
}

// GetMyDriverProfile operation middleware
func (siw *ServerInterfaceWrapper) GetMyDriverProfile(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyDriverProfile(c)
}

// CreateDriverProfile operation middleware
func (siw *ServerInterfaceWrapper) CreateDriverProfile(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDriverProfile(c)
}

// UpdateDriverProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateDriverProfile(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateDriverProfile(c)
}

// GetDriverByUserId operation middleware
func (siw *ServerInterfaceWrapper) GetDriverByUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDriverByUserId(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/driver/filter", wrapper.GetFilteredDrivers)
	router.GET(options.BaseURL+"/driver/profile", wrapper.GetMyDriverProfile)
	router.POST(options.BaseURL+"/driver/profile", wrapper.CreateDriverProfile)
	router.PUT(options.BaseURL+"/driver/profile", wrapper.UpdateDriverProfile)
	router.GET(options.BaseURL+"/driver/:user_id", wrapper.GetDriverByUserId)
}

type GetFilteredDriversRequestObject struct {
	Body *GetFilteredDriversJSONRequestBody
}

type GetFilteredDriversResponseObject interface {
	VisitGetFilteredDriversResponse(w http.ResponseWriter) error
}

type GetFilteredDrivers200JSONResponse struct {
	Drivers *[]Driver `json:"drivers,omitempty"`
}

func (response GetFilteredDrivers200JSONResponse) VisitGetFilteredDriversResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFilteredDrivers404Response struct {
}

func (response GetFilteredDrivers404Response) VisitGetFilteredDriversResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetMyDriverProfileRequestObject struct {
}

type GetMyDriverProfileResponseObject interface {
	VisitGetMyDriverProfileResponse(w http.ResponseWriter) error
}

type GetMyDriverProfile200JSONResponse Driver

func (response GetMyDriverProfile200JSONResponse) VisitGetMyDriverProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMyDriverProfile401Response struct {
}

func (response GetMyDriverProfile401Response) VisitGetMyDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetMyDriverProfile404Response struct {
}

func (response GetMyDriverProfile404Response) VisitGetMyDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateDriverProfileRequestObject struct {
	Body *CreateDriverProfileJSONRequestBody
}

type CreateDriverProfileResponseObject interface {
	VisitCreateDriverProfileResponse(w http.ResponseWriter) error
}

type CreateDriverProfile201Response struct {
}

func (response CreateDriverProfile201Response) VisitCreateDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type CreateDriverProfile400Response struct {
}

func (response CreateDriverProfile400Response) VisitCreateDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateDriverProfile401Response struct {
}

func (response CreateDriverProfile401Response) VisitCreateDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateDriverProfileRequestObject struct {
	Body *UpdateDriverProfileJSONRequestBody
}

type UpdateDriverProfileResponseObject interface {
	VisitUpdateDriverProfileResponse(w http.ResponseWriter) error
}

type UpdateDriverProfile200Response struct {
}

func (response UpdateDriverProfile200Response) VisitUpdateDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateDriverProfile400Response struct {
}

func (response UpdateDriverProfile400Response) VisitUpdateDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateDriverProfile401Response struct {
}

func (response UpdateDriverProfile401Response) VisitUpdateDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateDriverProfile404Response struct {
}

func (response UpdateDriverProfile404Response) VisitUpdateDriverProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetDriverByUserIdRequestObject struct {
	UserId int64 `json:"user_id"`
}

type GetDriverByUserIdResponseObject interface {
	VisitGetDriverByUserIdResponse(w http.ResponseWriter) error
}

type GetDriverByUserId200JSONResponse Driver

func (response GetDriverByUserId200JSONResponse) VisitGetDriverByUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDriverByUserId404Response struct {
}

func (response GetDriverByUserId404Response) VisitGetDriverByUserIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /driver/filter)
	GetFilteredDrivers(ctx context.Context, request GetFilteredDriversRequestObject) (GetFilteredDriversResponseObject, error)
	// Get my driver profile
	// (GET /driver/profile)
	GetMyDriverProfile(ctx context.Context, request GetMyDriverProfileRequestObject) (GetMyDriverProfileResponseObject, error)
	// Create driver profile
	// (POST /driver/profile)
	CreateDriverProfile(ctx context.Context, request CreateDriverProfileRequestObject) (CreateDriverProfileResponseObject, error)
	// Update driver profile
	// (PUT /driver/profile)
	UpdateDriverProfile(ctx context.Context, request UpdateDriverProfileRequestObject) (UpdateDriverProfileResponseObject, error)

	// (GET /driver/{user_id})
	GetDriverByUserId(ctx context.Context, request GetDriverByUserIdRequestObject) (GetDriverByUserIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetFilteredDrivers operation middleware
func (sh *strictHandler) GetFilteredDrivers(ctx *gin.Context) {
	var request GetFilteredDriversRequestObject

	var body GetFilteredDriversJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetFilteredDrivers(ctx, request.(GetFilteredDriversRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFilteredDrivers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetFilteredDriversResponseObject); ok {
		if err := validResponse.VisitGetFilteredDriversResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyDriverProfile operation middleware
func (sh *strictHandler) GetMyDriverProfile(ctx *gin.Context) {
	var request GetMyDriverProfileRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyDriverProfile(ctx, request.(GetMyDriverProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyDriverProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetMyDriverProfileResponseObject); ok {
		if err := validResponse.VisitGetMyDriverProfileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDriverProfile operation middleware
func (sh *strictHandler) CreateDriverProfile(ctx *gin.Context) {
	var request CreateDriverProfileRequestObject

	var body CreateDriverProfileJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDriverProfile(ctx, request.(CreateDriverProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDriverProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateDriverProfileResponseObject); ok {
		if err := validResponse.VisitCreateDriverProfileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDriverProfile operation middleware
func (sh *strictHandler) UpdateDriverProfile(ctx *gin.Context) {
	var request UpdateDriverProfileRequestObject

	var body UpdateDriverProfileJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDriverProfile(ctx, request.(UpdateDriverProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDriverProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateDriverProfileResponseObject); ok {
		if err := validResponse.VisitUpdateDriverProfileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDriverByUserId operation middleware
func (sh *strictHandler) GetDriverByUserId(ctx *gin.Context, userId int64) {
	var request GetDriverByUserIdRequestObject

	request.UserId = userId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDriverByUserId(ctx, request.(GetDriverByUserIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDriverByUserId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetDriverByUserIdResponseObject); ok {
		if err := validResponse.VisitGetDriverByUserIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
