// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// CreateDriverJSONBody defines parameters for CreateDriver.
type CreateDriverJSONBody struct {
	// Lat Latitude (WGS84)
	Lat float32 `json:"lat"`

	// Lon Longitude (WGS84)
	Lon float32 `json:"lon"`

	// WorkEnds End of work time (ISO 8601)
	WorkEnds time.Time `json:"work_ends"`

	// WorkStarts Start of work time (ISO 8601)
	WorkStarts time.Time `json:"work_starts"`
}

// CreateDriverJSONRequestBody defines body for CreateDriver for application/json ContentType.
type CreateDriverJSONRequestBody CreateDriverJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new driver
	// (POST /drivers)
	CreateDriver(c *gin.Context)
	// Get driver by ID
	// (GET /drivers/{id})
	FindDriverById(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateDriver operation middleware
func (siw *ServerInterfaceWrapper) CreateDriver(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDriver(c)
}

// FindDriverById operation middleware
func (siw *ServerInterfaceWrapper) FindDriverById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FindDriverById(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/drivers", wrapper.CreateDriver)
	router.GET(options.BaseURL+"/drivers/:id", wrapper.FindDriverById)
}

type CreateDriverRequestObject struct {
	Body *CreateDriverJSONRequestBody
}

type CreateDriverResponseObject interface {
	VisitCreateDriverResponse(w http.ResponseWriter) error
}

type CreateDriver201JSONResponse struct {
	// Id ID of the newly created driver
	Id int `json:"id"`
}

func (response CreateDriver201JSONResponse) VisitCreateDriverResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDriver400Response struct {
}

func (response CreateDriver400Response) VisitCreateDriverResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type FindDriverByIdRequestObject struct {
	Id int `json:"id"`
}

type FindDriverByIdResponseObject interface {
	VisitFindDriverByIdResponse(w http.ResponseWriter) error
}

type FindDriverById200JSONResponse struct {
	Id         int        `json:"id"`
	Lat        *float32   `json:"lat,omitempty"`
	Lon        *float32   `json:"lon,omitempty"`
	Rating     *float32   `json:"rating,omitempty"`
	WorkEnds   *time.Time `json:"work_ends,omitempty"`
	WorkStarts *time.Time `json:"work_starts,omitempty"`
}

func (response FindDriverById200JSONResponse) VisitFindDriverByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindDriverById404Response struct {
}

func (response FindDriverById404Response) VisitFindDriverByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new driver
	// (POST /drivers)
	CreateDriver(ctx context.Context, request CreateDriverRequestObject) (CreateDriverResponseObject, error)
	// Get driver by ID
	// (GET /drivers/{id})
	FindDriverById(ctx context.Context, request FindDriverByIdRequestObject) (FindDriverByIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateDriver operation middleware
func (sh *strictHandler) CreateDriver(ctx *gin.Context) {
	var request CreateDriverRequestObject

	var body CreateDriverJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDriver(ctx, request.(CreateDriverRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDriver")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateDriverResponseObject); ok {
		if err := validResponse.VisitCreateDriverResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindDriverById operation middleware
func (sh *strictHandler) FindDriverById(ctx *gin.Context, id int) {
	var request FindDriverByIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FindDriverById(ctx, request.(FindDriverByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindDriverById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(FindDriverByIdResponseObject); ok {
		if err := validResponse.VisitFindDriverByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
