// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"time"
)

// FreelyAvailable defines model for FreelyAvailable.
type FreelyAvailable struct {
	// EnRouteOrder Accept en-route orders along the way
	EnRouteOrder *bool `json:"en_route_order,omitempty"`

	// FromDate Start of availability period
	FromDate     time.Time `json:"from_date"`
	FromLocation Location  `json:"from_location"`

	// TariffPerKm Price per 1 km
	TariffPerKm *float32 `json:"tariff_per_km,omitempty"`

	// ToDate End of availability period
	ToDate time.Time `json:"to_date"`

	// ToLocations Destination locations
	ToLocations *[]Location `json:"to_locations,omitempty"`
}

// FreelyAvailableDriverResponse defines model for FreelyAvailableDriverResponse.
type FreelyAvailableDriverResponse struct {
	// Distance Distance in meters from query point to driver's from_location
	Distance float32 `json:"distance"`

	// EnRouteOrder Accept en-route orders along the way
	EnRouteOrder *bool     `json:"en_route_order,omitempty"`
	FromDate     time.Time `json:"from_date"`
	FromLocation Location  `json:"from_location"`

	// Name Driver display name
	Name         string   `json:"name"`
	ProfileImage *string  `json:"profile_image,omitempty"`
	Rating       *float32 `json:"rating,omitempty"`

	// TariffPerKm Price per 1 km
	TariffPerKm *float32    `json:"tariff_per_km,omitempty"`
	ToDate      time.Time   `json:"to_date"`
	ToLocations *[]Location `json:"to_locations,omitempty"`
	UserId      int64       `json:"user_id"`
}

// FreelyAvailableResponse defines model for FreelyAvailableResponse.
type FreelyAvailableResponse struct {
	// EnRouteOrder Accept en-route orders along the way
	EnRouteOrder *bool     `json:"en_route_order,omitempty"`
	FromDate     time.Time `json:"from_date"`
	FromLocation Location  `json:"from_location"`

	// TariffPerKm Price per 1 km
	TariffPerKm *float32    `json:"tariff_per_km,omitempty"`
	ToDate      time.Time   `json:"to_date"`
	ToLocations *[]Location `json:"to_locations,omitempty"`
	UserId      int64       `json:"user_id"`
}

// GetFreelyAvailableDriversRequest defines model for GetFreelyAvailableDriversRequest.
type GetFreelyAvailableDriversRequest struct {
	// EnRouteOrder Filter by en-route order acceptance
	EnRouteOrder *bool `json:"en_route_order,omitempty"`

	// MaxTariff Maximum tariff per km
	MaxTariff *float32 `json:"max_tariff,omitempty"`

	// MinTariff Minimum tariff per km
	MinTariff *float32 `json:"min_tariff,omitempty"`

	// UserLat User latitude (WGS84)
	UserLat float32 `json:"user_lat"`

	// UserLon User longitude (WGS84)
	UserLon float32 `json:"user_lon"`
}

// Location defines model for Location.
type Location struct {
	// Address Reverse geocoded address
	Address *string `json:"address,omitempty"`

	// Lat Latitude (WGS84)
	Lat float32 `json:"lat"`

	// Lon Longitude (WGS84)
	Lon float32 `json:"lon"`
}

// CreateFreelyAvailableJSONRequestBody defines body for CreateFreelyAvailable for application/json ContentType.
type CreateFreelyAvailableJSONRequestBody = FreelyAvailable

// UpdateFreelyAvailableJSONRequestBody defines body for UpdateFreelyAvailable for application/json ContentType.
type UpdateFreelyAvailableJSONRequestBody = FreelyAvailable

// GetFreelyAvailableDriversJSONRequestBody defines body for GetFreelyAvailableDrivers for application/json ContentType.
type GetFreelyAvailableDriversJSONRequestBody = GetFreelyAvailableDriversRequest
