// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geolocation_persistent.sql

package sqlc

import (
	"context"
)

const findWithinRadiusDrivers = `-- name: FindWithinRadiusDrivers :many
WITH
	center AS (
		SELECT 
			$1::REAL AS lat, 
			$2::REAL AS lon,
			$3::INTEGER AS radius,
			ST_SetSRID(ST_MakePoint(lon, lat), 4326)::GEOGRAPHY AS geog,
			-- TODO: change resolution to bigger of h3
			-- h3_latlng_to_cell(lat, lon, 9) AS cell
			h3_latlng_to_cell(geog, 9) AS cell
	),
	covering AS (
		SELECT h3_grid_disk(cell, (ceil(radius / 350.0)::INTEGER + 1)) AS cell
		FROM center
	)
SELECT
	d.id,
	ST_X(d.location::GEOMETRY)::REAL AS lon,
	ST_Y(d.location::GEOMETRY)::REAL AS lat,
	ST_Distance(d.location, center.geog) AS distance_meters
FROM
	driver AS d
	CROSS JOIN center
	JOIN covering ON d.h3_res9 = covering.cell
WHERE
	d.is_available
	AND ST_DWithin(d.location, center.geog, center.radius)
ORDER BY d.location <-> center.geog
LIMIT 50
`

type FindWithinRadiusDriversParams struct {
	Column1 float32
	Column2 float32
	Column3 int32
}

type FindWithinRadiusDriversRow struct {
	ID             int64
	Lon            float32
	Lat            float32
	DistanceMeters interface{}
}

func (q *Queries) FindWithinRadiusDrivers(ctx context.Context, arg FindWithinRadiusDriversParams) ([]FindWithinRadiusDriversRow, error) {
	rows, err := q.db.Query(ctx, findWithinRadiusDrivers, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindWithinRadiusDriversRow
	for rows.Next() {
		var i FindWithinRadiusDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.Lon,
			&i.Lat,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
