// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geolocation_realtime.sql

package sqlc

import (
	"context"
)

const createDriverRealtime = `-- name: CreateDriverRealtime :exec

INSERT INTO driver_realtime (driver_id)
VALUES ($1)
`

// ---------------------  *Single driver* --------------------
func (q *Queries) CreateDriverRealtime(ctx context.Context, driverID uint32) error {
	_, err := q.db.Exec(ctx, createDriverRealtime, driverID)
	return err
}

const createOrUpdateDriverRealtime = `-- name: CreateOrUpdateDriverRealtime :exec
INSERT INTO driver_realtime (
    driver_id,
	updated_at,
    realtime_location,
    average_speed,
    predicted_bearing
) VALUES (
    $1::INTEGER,
	now(),
    $2::GEOGRAPHY,
    $3::REAL,
    $4::REAL
)
ON CONFLICT (driver_id) DO UPDATE SET
	updated_at = EXCLUDED.updated_at,
    realtime_location = EXCLUDED.realtime_location,
    average_speed = EXCLUDED.average_speed,
    predicted_bearing = EXCLUDED.predicted_bearing
`

type CreateOrUpdateDriverRealtimeParams struct {
	Column1 int32
	Column2 interface{}
	Column3 float32
	Column4 float32
}

// TODO: replace "CreateRealtime" with this
func (q *Queries) CreateOrUpdateDriverRealtime(ctx context.Context, arg CreateOrUpdateDriverRealtimeParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateDriverRealtime,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const findClosestDriversRealtime = `-- name: FindClosestDriversRealtime :many

WITH point AS (
    SELECT ST_SetSRID(ST_MakePoint($2::REAL, $1::REAL), 4326)::GEOGRAPHY AS geog -- lon ($2), lat ($1) order
)
SELECT
	dr.driver_id,
	ST_Distance(dr.realtime_location, point.geog)::INTEGER AS distance_meters
FROM
	driver_realtime AS dr
	CROSS JOIN point
ORDER BY dr.realtime_location <-> point.geog
LIMIT 10
`

type FindClosestDriversRealtimeParams struct {
	Column1 float32
	Column2 float32
}

type FindClosestDriversRealtimeRow struct {
	DriverID       uint32
	DistanceMeters int32
}

// ---------------------  *Find Closest drivers* implementations --------------------
// 1. GiST index -> 2. ORDER BY closest "<->"
func (q *Queries) FindClosestDriversRealtime(ctx context.Context, arg FindClosestDriversRealtimeParams) ([]FindClosestDriversRealtimeRow, error) {
	rows, err := q.db.Query(ctx, findClosestDriversRealtime, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindClosestDriversRealtimeRow
	for rows.Next() {
		var i FindClosestDriversRealtimeRow
		if err := rows.Scan(&i.DriverID, &i.DistanceMeters); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findClosestDriversRealtimeH3 = `-- name: FindClosestDriversRealtimeH3 :many
WITH 
    point AS (
        SELECT 
            $1::REAL AS lat,
            $2::REAL AS lon,
            ST_SetSRID(ST_MakePoint($2, $1), 4326)::GEOGRAPHY AS geog
    ),
    coarse_cells AS (
		-- TODO: change resolution to bigger of h3
        SELECT h3_grid_disk(h3_latlng_to_cell(point.geog::GEOMETRY, 2), 1) AS cell
        FROM point
    )
SELECT
	dr.driver_id,
  	ST_Distance(dr.realtime_location, point.geog)::INTEGER AS distance_meters
FROM
	driver_realtime AS dr
	CROSS JOIN point
    JOIN coarse_cells AS cc ON dr.coarse_h3 = cc.cell
ORDER BY dr.realtime_location <-> point.geog
LIMIT 10
`

type FindClosestDriversRealtimeH3Params struct {
	Column1 float32
	Column2 float32
}

type FindClosestDriversRealtimeH3Row struct {
	DriverID       uint32
	DistanceMeters int32
}

// 1. H3 cells = [area] -> 2. GiST index = [exact distance] withith [area] -> 3. ORDER BY closest "<->"
func (q *Queries) FindClosestDriversRealtimeH3(ctx context.Context, arg FindClosestDriversRealtimeH3Params) ([]FindClosestDriversRealtimeH3Row, error) {
	rows, err := q.db.Query(ctx, findClosestDriversRealtimeH3, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindClosestDriversRealtimeH3Row
	for rows.Next() {
		var i FindClosestDriversRealtimeH3Row
		if err := rows.Scan(&i.DriverID, &i.DistanceMeters); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findClosestWithinRadiusDriversRealtime = `-- name: FindClosestWithinRadiusDriversRealtime :many
WITH user_location AS (
	SELECT st_setsrid(st_makepoint($2::REAL, $1::REAL), 4326)::GEOGRAPHY AS geog -- lon ($2), lat ($1) order
)
SELECT
	dr.driver_id,
	ST_X(dr.realtime_location::GEOMETRY)::REAL AS lon,
	ST_Y(dr.realtime_location::GEOMETRY)::REAL AS lat,
	st_distance(dr.realtime_location, user_location.geog)::INTEGER AS distance_meters
FROM
	driver_realtime AS dr
	CROSS JOIN user_location
WHERE st_dwithin(dr.realtime_location, user_location.geog, $3::INTEGER) -- radius in meters
ORDER BY dr.realtime_location <-> user_location.geog
LIMIT 20
`

type FindClosestWithinRadiusDriversRealtimeParams struct {
	Column1 float32
	Column2 float32
	Column3 int32
}

type FindClosestWithinRadiusDriversRealtimeRow struct {
	DriverID       uint32
	Lon            float32
	Lat            float32
	DistanceMeters int32
}

// "<->" uses GiST indexing, it is faster over:
// "ORDER BY distance_meters ASC"
func (q *Queries) FindClosestWithinRadiusDriversRealtime(ctx context.Context, arg FindClosestWithinRadiusDriversRealtimeParams) ([]FindClosestWithinRadiusDriversRealtimeRow, error) {
	rows, err := q.db.Query(ctx, findClosestWithinRadiusDriversRealtime, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindClosestWithinRadiusDriversRealtimeRow
	for rows.Next() {
		var i FindClosestWithinRadiusDriversRealtimeRow
		if err := rows.Scan(
			&i.DriverID,
			&i.Lon,
			&i.Lat,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWithinRadiusDriversRealtimeH3 = `-- name: FindWithinRadiusDriversRealtimeH3 :many

WITH
	center AS (
		SELECT 
			$1::REAL AS lat, 
			$2::REAL AS lon,
			$3::INTEGER AS radius,
			-- TODO: move to params
			$4::INTEGER AS result_limit,
			ST_SetSRID(ST_MakePoint(lon, lat), 4326)::GEOGRAPHY AS geog,
			h3_latlng_to_cell(lat, lon, 9) AS cell
	),
	covering AS (
		SELECT h3_grid_disk(cell, (ceil(radius / 350.0)::INTEGER + 1)) AS cell
		FROM center
	)
SELECT
	dr.driver_id,
	ST_Distance(dr.realtime_location, center.geog) AS distance_meters
FROM driver_realtime AS dr
CROSS JOIN center
JOIN covering ON dr.coarse_h3 = covering.cell
WHERE ST_DWithin(dr.realtime_location, center.geog, center.radius)
ORDER BY dr.realtime_location <-> center.geog
LIMIT center.result_limit
`

type FindWithinRadiusDriversRealtimeH3Params struct {
	Column1 float32
	Column2 float32
	Column3 int32
	Column4 int32
}

type FindWithinRadiusDriversRealtimeH3Row struct {
	DriverID       uint32
	DistanceMeters interface{}
}

// ---------------------  *Find Within Radius drivers* implementations --------------------
func (q *Queries) FindWithinRadiusDriversRealtimeH3(ctx context.Context, arg FindWithinRadiusDriversRealtimeH3Params) ([]FindWithinRadiusDriversRealtimeH3Row, error) {
	rows, err := q.db.Query(ctx, findWithinRadiusDriversRealtimeH3,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindWithinRadiusDriversRealtimeH3Row
	for rows.Next() {
		var i FindWithinRadiusDriversRealtimeH3Row
		if err := rows.Scan(&i.DriverID, &i.DistanceMeters); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDriverRealtimeByID = `-- name: GetDriverRealtimeByID :one
SELECT 
	driver_id,
	ST_X(realtime_location::GEOMETRY)::REAL AS lon,
	ST_Y(realtime_location::GEOMETRY)::REAL AS lat
FROM driver_realtime
WHERE 
	driver_id = $1
	-- TODO: do Garbage Collecting instead (Vacuum)
	-- AND realtime_updated_at > NOW() - INTERVAL '5 minutes'
`

type GetDriverRealtimeByIDRow struct {
	DriverID uint32
	Lon      float32
	Lat      float32
}

func (q *Queries) GetDriverRealtimeByID(ctx context.Context, driverID uint32) (GetDriverRealtimeByIDRow, error) {
	row := q.db.QueryRow(ctx, getDriverRealtimeByID, driverID)
	var i GetDriverRealtimeByIDRow
	err := row.Scan(&i.DriverID, &i.Lon, &i.Lat)
	return i, err
}

const updateDriverRealtime = `-- name: UpdateDriverRealtime :exec
UPDATE driver_realtime
SET
	updated_at = CURRENT_TIMESTAMP,
	realtime_location = st_setsrid(st_makepoint($3::REAL, $2::REAL), 4326), -- lon ($3), lat ($2) order
	predicted_bearing = $4::REAL,
	average_speed = $5::REAL
WHERE
	driver_id = $1
`

type UpdateDriverRealtimeParams struct {
	DriverID uint32
	Column2  float32
	Column3  float32
	Column4  float32
	Column5  float32
}

func (q *Queries) UpdateDriverRealtime(ctx context.Context, arg UpdateDriverRealtimeParams) error {
	_, err := q.db.Exec(ctx, updateDriverRealtime,
		arg.DriverID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}
