// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Driver struct {
	ID          int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	WorkStarts  pgtype.Time
	WorkEnds    pgtype.Time
	Rating      pgtype.Float4
	IsAvailable pgtype.Bool
	LastSeen    pgtype.Timestamptz
	Location    interface{}
	H3Res5      interface{}
	H3Res6      interface{}
	H3Res7      interface{}
}

type DriverRealtime struct {
	DriverID            uint32
	UpdatedAt           pgtype.Timestamp
	RealtimeLocation    interface{}
	AverageSpeed        pgtype.Float4
	PredictedBearing    pgtype.Float4
	CoarseH3            interface{}
	DestinationLocation interface{}
	DestinationTime     pgtype.Timestamp
}
