// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moving_driver.sql

package sqlc

import (
	"context"
	"time"
)

const deleteStaleMovingDrivers = `-- name: DeleteStaleMovingDrivers :exec
DELETE FROM moving_driver
WHERE updated_at < NOW() - ($1::TEXT)::INTERVAL
`

func (q *Queries) DeleteStaleMovingDrivers(ctx context.Context, cutoff string) error {
	_, err := q.db.Exec(ctx, deleteStaleMovingDrivers, cutoff)
	return err
}

const getClosestWithinRadiusMovingDriver = `-- name: GetClosestWithinRadiusMovingDriver :many
WITH user_location AS (
	SELECT st_setsrid(st_makepoint($2::REAL, $3::REAL), 4326)::GEOGRAPHY AS geog
)
SELECT
	md.driver_id,
	st_distance(md.realtime_location, user_location.geog)::INTEGER AS distance_meters,
	ST_X(md.realtime_location::GEOMETRY)::REAL AS lon,
	ST_Y(md.realtime_location::GEOMETRY)::REAL AS lat,
	travel_time,
	path_meters
FROM moving_driver AS md
CROSS JOIN user_location
WHERE st_dwithin(md.realtime_location, user_location.geog, $1::INTEGER)
ORDER BY md.realtime_location <-> user_location.geog
LIMIT 20
`

type GetClosestWithinRadiusMovingDriverParams struct {
	Radius int32
	Lon    float32
	Lat    float32
}

type GetClosestWithinRadiusMovingDriverRow struct {
	DriverID       int64
	DistanceMeters int32
	Lon            float32
	Lat            float32
	TravelTime     time.Time
	PathMeters     int32
}

func (q *Queries) GetClosestWithinRadiusMovingDriver(ctx context.Context, arg GetClosestWithinRadiusMovingDriverParams) ([]GetClosestWithinRadiusMovingDriverRow, error) {
	rows, err := q.db.Query(ctx, getClosestWithinRadiusMovingDriver, arg.Radius, arg.Lon, arg.Lat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClosestWithinRadiusMovingDriverRow
	for rows.Next() {
		var i GetClosestWithinRadiusMovingDriverRow
		if err := rows.Scan(
			&i.DriverID,
			&i.DistanceMeters,
			&i.Lon,
			&i.Lat,
			&i.TravelTime,
			&i.PathMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovingDriverByID = `-- name: GetMovingDriverByID :one
SELECT 
	driver_id,
	ST_X(realtime_location::GEOMETRY)::REAL AS lon,
	ST_Y(realtime_location::GEOMETRY)::REAL AS lat,
	travel_time,
	path_meters
FROM moving_driver
WHERE driver_id = $1
`

type GetMovingDriverByIDRow struct {
	DriverID   int64
	Lon        float32
	Lat        float32
	TravelTime time.Time
	PathMeters int32
}

func (q *Queries) GetMovingDriverByID(ctx context.Context, driverID int64) (GetMovingDriverByIDRow, error) {
	row := q.db.QueryRow(ctx, getMovingDriverByID, driverID)
	var i GetMovingDriverByIDRow
	err := row.Scan(
		&i.DriverID,
		&i.Lon,
		&i.Lat,
		&i.TravelTime,
		&i.PathMeters,
	)
	return i, err
}

const updateMovingDriver = `-- name: UpdateMovingDriver :exec
INSERT INTO moving_driver (
    driver_id,
    updated_at,
	realtime_location,
	travel_time,
	path_meters
) VALUES (
	$1,
    now(),
	ST_SetSRID(ST_MakePoint($4::REAL, $5::REAL), 4326),
    $2,
	$3
)
ON CONFLICT (driver_id) DO UPDATE SET
    updated_at = EXCLUDED.updated_at,
    realtime_location = EXCLUDED.realtime_location,
    travel_time = EXCLUDED.travel_time,
	path_meters = EXCLUDED.path_meters
`

type UpdateMovingDriverParams struct {
	DriverID   int64
	TravelTime time.Time
	PathMeters int32
	Lon        float32
	Lat        float32
}

func (q *Queries) UpdateMovingDriver(ctx context.Context, arg UpdateMovingDriverParams) error {
	_, err := q.db.Exec(ctx, updateMovingDriver,
		arg.DriverID,
		arg.TravelTime,
		arg.PathMeters,
		arg.Lon,
		arg.Lat,
	)
	return err
}
