// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/protobuf/geolocation/gps_realtime_channel/gps_update.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPSUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []*Point               `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	Timestamps    []int64                `protobuf:"varint,2,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPSUpdate) Reset() {
	*x = GPSUpdate{}
	mi := &file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPSUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSUpdate) ProtoMessage() {}

func (x *GPSUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSUpdate.ProtoReflect.Descriptor instead.
func (*GPSUpdate) Descriptor() ([]byte, []int) {
	return file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDescGZIP(), []int{0}
}

func (x *GPSUpdate) GetCoordinates() []*Point {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *GPSUpdate) GetTimestamps() []int64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto protoreflect.FileDescriptor

const file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDesc = "" +
	"\n" +
	">api/protobuf/geolocation/gps_realtime_channel/gps_update.proto\x12\x02pb\"X\n" +
	"\tGPSUpdate\x12+\n" +
	"\vcoordinates\x18\x01 \x03(\v2\t.pb.PointR\vcoordinates\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x02 \x03(\x03R\n" +
	"timestamps\"A\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitudeB\aZ\x05./;pbb\x06proto3"

var (
	file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDescOnce sync.Once
	file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDescData []byte
)

func file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDescGZIP() []byte {
	file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDescOnce.Do(func() {
		file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDesc), len(file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDesc)))
	})
	return file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDescData
}

var file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_goTypes = []any{
	(*GPSUpdate)(nil), // 0: pb.GPSUpdate
	(*Point)(nil),     // 1: pb.Point
}
var file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_depIdxs = []int32{
	1, // 0: pb.GPSUpdate.coordinates:type_name -> pb.Point
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_init() }
func file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_init() {
	if File_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDesc), len(file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_goTypes,
		DependencyIndexes: file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_depIdxs,
		MessageInfos:      file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_msgTypes,
	}.Build()
	File_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto = out.File
	file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_goTypes = nil
	file_api_protobuf_geolocation_gps_realtime_channel_gps_update_proto_depIdxs = nil
}
