// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/protobuf/geolocation/gps_realtime_channel/gps_get.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverRealtime struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DriverId int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Distance float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Time     uint32                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	// repeated float points = 4;
	Points        []*Coordinates `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRealtime) Reset() {
	*x = DriverRealtime{}
	mi := &file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRealtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRealtime) ProtoMessage() {}

func (x *DriverRealtime) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRealtime.ProtoReflect.Descriptor instead.
func (*DriverRealtime) Descriptor() ([]byte, []int) {
	return file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDescGZIP(), []int{0}
}

func (x *DriverRealtime) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverRealtime) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *DriverRealtime) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *DriverRealtime) GetPoints() []*Coordinates {
	if x != nil {
		return x.Points
	}
	return nil
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []float32              `protobuf:"fixed32,1,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDescGZIP(), []int{1}
}

func (x *Coordinates) GetCoordinates() []float32 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

var File_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto protoreflect.FileDescriptor

const file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDesc = "" +
	"\n" +
	";api/protobuf/geolocation/gps_realtime_channel/gps_get.proto\x12\x02pb\"\x86\x01\n" +
	"\x0eDriverRealtime\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\rR\bdriverId\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x12\x12\n" +
	"\x04time\x18\x03 \x01(\rR\x04time\x12'\n" +
	"\x06points\x18\x04 \x03(\v2\x0f.pb.CoordinatesR\x06points\"/\n" +
	"\vCoordinates\x12 \n" +
	"\vcoordinates\x18\x01 \x03(\x02R\vcoordinatesB\aZ\x05./;pbb\x06proto3"

var (
	file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDescOnce sync.Once
	file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDescData []byte
)

func file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDescGZIP() []byte {
	file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDescOnce.Do(func() {
		file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDesc), len(file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDesc)))
	})
	return file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDescData
}

var file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_goTypes = []any{
	(*DriverRealtime)(nil), // 0: pb.DriverRealtime
	(*Coordinates)(nil),    // 1: pb.Coordinates
}
var file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_depIdxs = []int32{
	1, // 0: pb.DriverRealtime.points:type_name -> pb.Coordinates
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_init() }
func file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_init() {
	if File_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDesc), len(file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_goTypes,
		DependencyIndexes: file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_depIdxs,
		MessageInfos:      file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_msgTypes,
	}.Build()
	File_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto = out.File
	file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_goTypes = nil
	file_api_protobuf_geolocation_gps_realtime_channel_gps_get_proto_depIdxs = nil
}
